# pa_embed_text_file(<target> <input file> <output .cpp> <C++ function name>)
#
# Compile a text file into <target> as a function that returns its contents:
#
#   pa_embed_text_file(MyLib data/Tools.json ${CMAKE_BINARY_DIR}/Tools.cpp "My::Space::tools_json")
#
# generates Tools.cpp defining `const std::string& My::Space::tools_json()`. Declare
# that function in a header of your own. The file is embedded as a byte array rather
# than a string literal, so its size and content are not limited by compilers'
# string-literal rules (e.g. MSVC's 16 KB limit).
#
# The .cpp is regenerated when <input file> changes: the file is registered as a
# configure dependency, so the next build re-runs CMake first.

function(pa_embed_text_file target input output function_name)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${input})

    file(READ ${input} hex HEX)
    string(LENGTH "${hex}" hex_length)
    set(bytes "")
    set(column 0)
    set(position 0)
    while(position LESS hex_length)
        string(SUBSTRING "${hex}" ${position} 2 byte)
        string(APPEND bytes "0x${byte},")
        math(EXPR position "${position} + 2")
        math(EXPR column "${column} + 1")
        if(column EQUAL 24)
            string(APPEND bytes "\n    ")
            set(column 0)
        endif()
    endwhile()

    # "A::B::name" -> namespaces A, B and function `name`
    string(REPLACE "::" ";" parts "${function_name}")
    list(POP_BACK parts name)
    set(open_namespaces "")
    set(close_namespaces "")
    foreach(part ${parts})
        string(APPEND open_namespaces "namespace ${part}{\n")
        string(APPEND close_namespaces "}\n")
    endforeach()

    file(RELATIVE_PATH input_name ${CMAKE_CURRENT_SOURCE_DIR} ${input})
    set(content
"//  Generated by cmake/EmbedTextFile.cmake from ${input_name}. Do not edit.

#include <string>

${open_namespaces}

static const unsigned char EMBEDDED_TEXT[] = {
    ${bytes}0x00
};

const std::string& ${name}(){
    static const std::string text((const char*)EMBEDDED_TEXT, sizeof(EMBEDDED_TEXT) - 1);
    return text;
}

${close_namespaces}")

    # Only touch the output when it changes, so unrelated reconfigures don't rebuild it.
    set(existing "")
    if(EXISTS ${output})
        file(READ ${output} existing)
    endif()
    if(NOT existing STREQUAL content)
        file(WRITE ${output} "${content}")
    endif()

    target_sources(${target} PRIVATE ${output})
endfunction()
