
QT += core gui
QT += serialport
QT += multimedia
QT += multimediawidgets

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

INCLUDEPATH += ../
INCLUDEPATH += ../../Internal/
INCLUDEPATH += Source/
RESOURCES += ../Common/Qt/qdarkstyle/dark/style.qrc

CONFIG += force_debug_info

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

exists(../../Internal/SerialPrograms/TelemetryURLs.h){
    DEFINES += PA_OFFICIAL
}

win32-g++{
    CONFIG += c++1z

    QMAKE_CXXFLAGS += -march=nehalem
    QMAKE_CXXFLAGS += -Wno-comment
    QMAKE_CXXFLAGS += -Wno-ignored-attributes
#    QMAKE_CXXFLAGS += -Wnarrowing
#    QMAKE_CXXFLAGS += -Wno-unused-parameter
#    QMAKE_CXXFLAGS += -Wno-unused-function
#    QMAKE_CXXFLAGS += -Wno-missing-field-initializers

    QMAKE_CXXFLAGS += -D_WIN32_WINNT=0x0601

    DEFINES += WIN32
    DEFINES += PA_TESSERACT
    DEFINES += PA_AutoDispatch_08_Nehalem
    LIBS += ../SerialPrograms/tesseractPA.lib

    DEFINES += WIN32
    DEFINES += PA_SLEEPY
    LIBS += ../SerialPrograms/Sleepy.lib
}
win32-msvc{
    QMAKE_CXXFLAGS += /std:c++latest
    QMAKE_CXXFLAGS += -MP

    DEFINES += WIN32
    DEFINES += PA_TESSERACT
    DEFINES += PA_AutoDispatch_08_Nehalem
    LIBS += ../SerialPrograms/tesseractPA.lib

    DEFINES += WIN32
    DEFINES += PA_SLEEPY
    LIBS += ../SerialPrograms/Sleepy.lib
}
macx{
    QMAKE_CXXFLAGS += -std=c++14

    DEFINES += PA_AutoDispatch_08_Nehalem

    QMAKE_INFO_PLIST = macos/Info.plist
}


SOURCES += \
    ../ClientSource/Connection/MessageLogger.cpp \
    ../ClientSource/Connection/PABotBase.cpp \
    ../ClientSource/Connection/PABotBaseConnection.cpp \
    ../ClientSource/Libraries/Logging.cpp \
    ../ClientSource/Libraries/MessageConverter.cpp \
    ../Common/CRC32.cpp \
    ../Common/Cpp/AsyncDispatcher.cpp \
    ../Common/Cpp/CancellableScope.cpp \
    ../Common/Cpp/CpuId.cpp \
    ../Common/Cpp/Exceptions.cpp \
    ../Common/Cpp/FireForgetDispatcher.cpp \
    ../Common/Cpp/LifetimeSanitizer.cpp \
    ../Common/Cpp/PanicDump.cpp \
    ../Common/Cpp/ParallelTaskRunner.cpp \
    ../Common/Cpp/PeriodicScheduler.cpp \
    ../Common/Cpp/PrettyPrint.cpp \
    ../Common/Cpp/SpinLock.cpp \
    ../Common/Cpp/Time.cpp \
    ../Common/Cpp/Unicode.cpp \
    ../Common/Microcontroller/DeviceRoutines.cpp \
    ../Common/NintendoSwitch/NintendoSwitch_Tools.cpp \
    ../Common/Qt/AutoHeightTable.cpp \
    ../Common/Qt/AutoWidthLineEdit.cpp \
    ../Common/Qt/CodeValidator.cpp \
    ../Common/Qt/CollapsibleGroupBox.cpp \
    ../Common/Qt/ExpressionEvaluator.cpp \
    ../Common/Qt/Options/BooleanCheckBox/BooleanCheckBoxBaseOption.cpp \
    ../Common/Qt/Options/BooleanCheckBox/BooleanCheckBoxBaseWidget.cpp \
    ../Common/Qt/Options/EditableTable/EditableTableBaseOption.cpp \
    ../Common/Qt/Options/EditableTable/EditableTableBaseWidget.cpp \
    ../Common/Qt/Options/FloatingPoint/FloatingPointBaseOption.cpp \
    ../Common/Qt/Options/FloatingPoint/FloatingPointBaseWidget.cpp \
    ../Common/Qt/Options/FossilTableBaseOption.cpp \
    ../Common/Qt/Options/MultiHostTableBaseOption.cpp \
    ../Common/Qt/Options/SimpleInteger/SimpleIntegerBaseOption.cpp \
    ../Common/Qt/Options/SimpleInteger/SimpleIntegerBaseWidget.cpp \
    ../Common/Qt/Options/String/StringBaseOption.cpp \
    ../Common/Qt/Options/String/StringBaseWidget.cpp \
    ../Common/Qt/Options/SwitchDate/SwitchDateBaseOption.cpp \
    ../Common/Qt/Options/SwitchDate/SwitchDateBaseWidget.cpp \
    ../Common/Qt/Options/TimeExpression/TimeExpressionBaseOption.cpp \
    ../Common/Qt/Options/TimeExpression/TimeExpressionBaseWidget.cpp \
    ../Common/Qt/QtJsonTools.cpp \
    Source/CommonFramework/AudioPipeline/AudioDisplayWidget.cpp \
    Source/CommonFramework/AudioPipeline/AudioFileLoader.cpp \
    Source/CommonFramework/AudioPipeline/AudioFormatUtils.cpp \
    Source/CommonFramework/AudioPipeline/AudioIODevice.cpp \
    Source/CommonFramework/AudioPipeline/AudioInfo.cpp \
    Source/CommonFramework/AudioPipeline/AudioSelector.cpp \
    Source/CommonFramework/AudioPipeline/AudioSelectorWidget.cpp \
    Source/CommonFramework/AudioPipeline/AudioTemplate.cpp \
    Source/CommonFramework/AudioPipeline/AudioThreadController.cpp \
    Source/CommonFramework/AudioPipeline/AudioWorker.cpp \
    Source/CommonFramework/AudioPipeline/FFTWorker.cpp \
    Source/CommonFramework/AudioPipeline/TimeSampleBuffer.cpp \
    Source/CommonFramework/AudioPipeline/TimeSampleBufferReader.cpp \
    Source/CommonFramework/AudioPipeline/WavFile.cpp \
    Source/CommonFramework/ControllerDevices/SerialSelector.cpp \
    Source/CommonFramework/ControllerDevices/SerialSelectorWidget.cpp \
    Source/CommonFramework/CrashDump.cpp \
    Source/CommonFramework/Environment/Environment.cpp \
    Source/CommonFramework/Environment/Environment_Linux.cpp \
    Source/CommonFramework/Environment/Environment_Windows.cpp \
    Source/CommonFramework/Environment/HardwareValidation.cpp \
    Source/CommonFramework/GlobalSettingsPanel.cpp \
    Source/CommonFramework/Globals.cpp \
    Source/CommonFramework/ImageMatch/CroppedImageDictionaryMatcher.cpp \
    Source/CommonFramework/ImageMatch/ExactImageDictionaryMatcher.cpp \
    Source/CommonFramework/ImageMatch/ExactImageMatcher.cpp \
    Source/CommonFramework/ImageMatch/FilterToAlpha.cpp \
    Source/CommonFramework/ImageMatch/ImageCropper.cpp \
    Source/CommonFramework/ImageMatch/ImageDiff.cpp \
    Source/CommonFramework/ImageMatch/ImageMatchOption.cpp \
    Source/CommonFramework/ImageMatch/ImageMatchResult.cpp \
    Source/CommonFramework/ImageMatch/ScaleBrightness.cpp \
    Source/CommonFramework/ImageMatch/SilhouetteDictionaryMatcher.cpp \
    Source/CommonFramework/ImageMatch/SubObjectTemplateMatcher.cpp \
    Source/CommonFramework/ImageMatch/WaterfillTemplateMatcher.cpp \
    Source/CommonFramework/ImageTools/BinaryImage_FilterRgb32.cpp \
    Source/CommonFramework/ImageTools/ColorClustering.cpp \
    Source/CommonFramework/ImageTools/FloatPixel.cpp \
    Source/CommonFramework/ImageTools/ImageBoxes.cpp \
    Source/CommonFramework/ImageTools/ImageFilter.cpp \
    Source/CommonFramework/ImageTools/ImageStats.cpp \
    Source/CommonFramework/ImageTools/SolidColorTest.cpp \
    Source/CommonFramework/ImageTypes/BinaryImage.cpp \
    Source/CommonFramework/ImageTypes/ImageReference.cpp \
    Source/CommonFramework/Inference/AnomalyDetector.cpp \
    Source/CommonFramework/Inference/AudioPerSpectrumDetectorBase.cpp \
    Source/CommonFramework/Inference/AudioTemplateCache.cpp \
    Source/CommonFramework/Inference/BlackBorderDetector.cpp \
    Source/CommonFramework/Inference/BlackScreenDetector.cpp \
    Source/CommonFramework/Inference/FrozenImageDetector.cpp \
    Source/CommonFramework/Inference/ImageMatchDetector.cpp \
    Source/CommonFramework/Inference/ImageTools.cpp \
    Source/CommonFramework/Inference/SpectrogramMatcher.cpp \
    Source/CommonFramework/Inference/StatAccumulator.cpp \
    Source/CommonFramework/InferenceInfra/AudioInferencePivot.cpp \
    Source/CommonFramework/InferenceInfra/InferenceRoutines.cpp \
    Source/CommonFramework/InferenceInfra/InferenceSession.cpp \
    Source/CommonFramework/InferenceInfra/VisualInferenceCallback.cpp \
    Source/CommonFramework/InferenceInfra/VisualInferencePivot.cpp \
    Source/CommonFramework/Language.cpp \
    Source/CommonFramework/Logging/FileWindowLogger.cpp \
    Source/CommonFramework/Logging/LoggerQt.cpp \
    Source/CommonFramework/Logging/OutputRedirector.cpp \
    Source/CommonFramework/Logging/QueuedLogger.cpp \
    Source/CommonFramework/Main.cpp \
    Source/CommonFramework/Notifications/EventNotificationOption.cpp \
    Source/CommonFramework/Notifications/EventNotificationsTable.cpp \
    Source/CommonFramework/Notifications/MessageAttachment.cpp \
    Source/CommonFramework/Notifications/ProgramNotifications.cpp \
    Source/CommonFramework/Notifications/SenderNotificationTable.cpp \
    Source/CommonFramework/OCR/OCR_DictionaryMatcher.cpp \
    Source/CommonFramework/OCR/OCR_DictionaryOCR.cpp \
    Source/CommonFramework/OCR/OCR_Filtering.cpp \
    Source/CommonFramework/OCR/OCR_LanguageOptionOCR.cpp \
    Source/CommonFramework/OCR/OCR_LargeDictionaryMatcher.cpp \
    Source/CommonFramework/OCR/OCR_NumberReader.cpp \
    Source/CommonFramework/OCR/OCR_RawOCR.cpp \
    Source/CommonFramework/OCR/OCR_Routines.cpp \
    Source/CommonFramework/OCR/OCR_SmallDictionaryMatcher.cpp \
    Source/CommonFramework/OCR/OCR_StringMatchResult.cpp \
    Source/CommonFramework/OCR/OCR_StringNormalization.cpp \
    Source/CommonFramework/OCR/OCR_TextMatcher.cpp \
    Source/CommonFramework/OCR/OCR_TrainingTools.cpp \
    Source/CommonFramework/Options/BatchOption/BatchOption.cpp \
    Source/CommonFramework/Options/BatchOption/GroupOption.cpp \
    Source/CommonFramework/Options/BooleanCheckBoxOption.cpp \
    Source/CommonFramework/Options/ConfigOption.cpp \
    Source/CommonFramework/Options/EditableTableOption.cpp \
    Source/CommonFramework/Options/EnumDropdownOption.cpp \
    Source/CommonFramework/Options/Environment/ProcessPriorityOption.cpp \
    Source/CommonFramework/Options/Environment/ProcessorLevelOption.cpp \
    Source/CommonFramework/Options/Environment/ThemeSelectorOption.cpp \
    Source/CommonFramework/Options/FixedCodeOption.cpp \
    Source/CommonFramework/Options/FloatingPointOption.cpp \
    Source/CommonFramework/Options/HiddenTextEditOption.cpp \
    Source/CommonFramework/Options/RandomCodeOption.cpp \
    Source/CommonFramework/Options/ScreenshotFormatOption.cpp \
    Source/CommonFramework/Options/SimpleIntegerOption.cpp \
    Source/CommonFramework/Options/StaticTextOption.cpp \
    Source/CommonFramework/Options/StringOption.cpp \
    Source/CommonFramework/Options/StringSelectOption.cpp \
    Source/CommonFramework/Options/TextEditOption.cpp \
    Source/CommonFramework/Panels/Panel.cpp \
    Source/CommonFramework/Panels/PanelList.cpp \
    Source/CommonFramework/Panels/PanelWidget.cpp \
    Source/CommonFramework/Panels/RunnableComputerProgram.cpp \
    Source/CommonFramework/Panels/RunnableComputerProgramWidget.cpp \
    Source/CommonFramework/Panels/RunnablePanel.cpp \
    Source/CommonFramework/Panels/RunnablePanelWidget.cpp \
    Source/CommonFramework/Panels/SettingsPanel.cpp \
    Source/CommonFramework/Panels/SettingsPanelWidget.cpp \
    Source/CommonFramework/PersistentSettings.cpp \
    Source/CommonFramework/Tools/BlackBorderCheck.cpp \
    Source/CommonFramework/Tools/BotBaseHandle.cpp \
    Source/CommonFramework/Tools/ConsoleHandle.cpp \
    Source/CommonFramework/Tools/ErrorDumper.cpp \
    Source/CommonFramework/Tools/InterruptableCommands.cpp \
    Source/CommonFramework/Tools/MultiConsoleErrors.cpp \
    Source/CommonFramework/Tools/ProgramEnvironment.cpp \
    Source/CommonFramework/Tools/StatsDatabase.cpp \
    Source/CommonFramework/Tools/StatsTracking.cpp \
    Source/CommonFramework/Tools/SuperControlSession.cpp \
    Source/CommonFramework/VideoPipeline/CameraImplementations.cpp \
    Source/CommonFramework/VideoPipeline/CameraSelector.cpp \
    Source/CommonFramework/VideoPipeline/CameraSelectorWidget.cpp \
    Source/CommonFramework/VideoPipeline/CameraWidgetQt5.cpp \
    Source/CommonFramework/VideoPipeline/CameraWidgetQt5v2.cpp \
    Source/CommonFramework/VideoPipeline/CameraWidgetQt6.cpp \
    Source/CommonFramework/VideoPipeline/VideoDisplayWidget.cpp \
    Source/CommonFramework/VideoPipeline/VideoOverlayWidget.cpp \
    Source/CommonFramework/VideoPipeline/VideoToolsQt5.cpp \
    Source/CommonFramework/Windows/ButtonDiagram.cpp \
    Source/CommonFramework/Windows/DpiScaler.cpp \
    Source/CommonFramework/Windows/MainWindow.cpp \
    Source/Integrations/DiscordIntegrationSettings.cpp \
    Source/Integrations/DiscordIntegrationTable.cpp \
    Source/Integrations/DiscordSettingsOption.cpp \
    Source/Integrations/DiscordWebhook.cpp \
    Source/Integrations/DiscordWebhookSettings.cpp \
    Source/Integrations/IntegrationsAPI.cpp \
    Source/Integrations/ProgramTracker.cpp \
    Source/Integrations/SleepyDiscordRunner.cpp \
    Source/Kernels/AbsFFT/Kernels_AbsFFT.cpp \
    Source/Kernels/AbsFFT/Kernels_AbsFFT_Core_Default.cpp \
    Source/Kernels/AbsFFT/Kernels_AbsFFT_Core_x86_AVX2.cpp \
    Source/Kernels/AbsFFT/Kernels_AbsFFT_Core_x86_SSE41.cpp \
    Source/Kernels/BinaryImageFilters/Kernels_BinaryImage_BasicFilters.cpp \
    Source/Kernels/BinaryImageFilters/Kernels_BinaryImage_BasicFilters_Core_64x16_x64_AVX2.cpp \
    Source/Kernels/BinaryImageFilters/Kernels_BinaryImage_BasicFilters_Core_64x4_Default.cpp \
    Source/Kernels/BinaryImageFilters/Kernels_BinaryImage_BasicFilters_Core_64x64_x64_AVX512.cpp \
    Source/Kernels/BinaryImageFilters/Kernels_BinaryImage_BasicFilters_Core_64x8_x64_SSE42.cpp \
    Source/Kernels/BinaryMatrix/Kernels_BinaryMatrix.cpp \
    Source/Kernels/BinaryMatrix/Kernels_BinaryMatrix_Core_64x16_x64_AVX2.cpp \
    Source/Kernels/BinaryMatrix/Kernels_BinaryMatrix_Core_64x32_x64_AVX512.cpp \
    Source/Kernels/BinaryMatrix/Kernels_BinaryMatrix_Core_64x4_Default.cpp \
    Source/Kernels/BinaryMatrix/Kernels_BinaryMatrix_Core_64x64_x64_AVX512.cpp \
    Source/Kernels/BinaryMatrix/Kernels_BinaryMatrix_Core_64x8_x64_SSE42.cpp \
    Source/Kernels/ImageFilters/Kernels_ImageFilter_Basic.cpp \
    Source/Kernels/ImageFilters/Kernels_ImageFilter_Basic_Default.cpp \
    Source/Kernels/ImageFilters/Kernels_ImageFilter_Basic_x64_AVX2.cpp \
    Source/Kernels/ImageFilters/Kernels_ImageFilter_Basic_x64_AVX512.cpp \
    Source/Kernels/ImageFilters/Kernels_ImageFilter_Basic_x64_SSE42.cpp \
    Source/Kernels/ImageScaleBrightness/Kernels_ImageScaleBrightness.cpp \
    Source/Kernels/ImageScaleBrightness/Kernels_ImageScaleBrightness_Default.cpp \
    Source/Kernels/ImageScaleBrightness/Kernels_ImageScaleBrightness_x64_AVX2.cpp \
    Source/Kernels/ImageScaleBrightness/Kernels_ImageScaleBrightness_x64_AVX512.cpp \
    Source/Kernels/ImageScaleBrightness/Kernels_ImageScaleBrightness_x64_SSE41.cpp \
    Source/Kernels/ImageStats/Kernels_ImagePixelSumSqr.cpp \
    Source/Kernels/ImageStats/Kernels_ImagePixelSumSqrDev.cpp \
    Source/Kernels/ImageStats/Kernels_ImagePixelSumSqrDev_Default.cpp \
    Source/Kernels/ImageStats/Kernels_ImagePixelSumSqrDev_x64_AVX2.cpp \
    Source/Kernels/ImageStats/Kernels_ImagePixelSumSqrDev_x64_AVX512.cpp \
    Source/Kernels/ImageStats/Kernels_ImagePixelSumSqrDev_x64_SSE41.cpp \
    Source/Kernels/ImageStats/Kernels_ImagePixelSumSqr_Default.cpp \
    Source/Kernels/ImageStats/Kernels_ImagePixelSumSqr_x64_AVX2.cpp \
    Source/Kernels/ImageStats/Kernels_ImagePixelSumSqr_x64_AVX512.cpp \
    Source/Kernels/ImageStats/Kernels_ImagePixelSumSqr_x64_SSE41.cpp \
    Source/Kernels/Waterfill/Kernels_Waterfill.cpp \
    Source/Kernels/Waterfill/Kernels_Waterfill_Core_64x16_x64_AVX2.cpp \
    Source/Kernels/Waterfill/Kernels_Waterfill_Core_64x32_x64_AVX512-GF.cpp \
    Source/Kernels/Waterfill/Kernels_Waterfill_Core_64x32_x64_AVX512.cpp \
    Source/Kernels/Waterfill/Kernels_Waterfill_Core_64x4_Default.cpp \
    Source/Kernels/Waterfill/Kernels_Waterfill_Core_64x64_x64_AVX512-GF.cpp \
    Source/Kernels/Waterfill/Kernels_Waterfill_Core_64x64_x64_AVX512.cpp \
    Source/Kernels/Waterfill/Kernels_Waterfill_Core_64x8_x64_SSE42.cpp \
    Source/Kernels/Waterfill/Kernels_Waterfill_Session.cpp \
    Source/NintendoSwitch/Commands/NintendoSwitch_Commands_Device.cpp \
    Source/NintendoSwitch/Commands/NintendoSwitch_Commands_DigitEntry.cpp \
    Source/NintendoSwitch/Commands/NintendoSwitch_Commands_PushButtons.cpp \
    Source/NintendoSwitch/Commands/NintendoSwitch_Commands_Routines.cpp \
    Source/NintendoSwitch/Framework/NintendoSwitch_CommandRow.cpp \
    Source/NintendoSwitch/Framework/NintendoSwitch_MultiSwitchProgram.cpp \
    Source/NintendoSwitch/Framework/NintendoSwitch_MultiSwitchProgramWidget.cpp \
    Source/NintendoSwitch/Framework/NintendoSwitch_MultiSwitchSystem.cpp \
    Source/NintendoSwitch/Framework/NintendoSwitch_MultiSwitchSystemWidget.cpp \
    Source/NintendoSwitch/Framework/NintendoSwitch_RunnableProgram.cpp \
    Source/NintendoSwitch/Framework/NintendoSwitch_RunnableProgramWidget.cpp \
    Source/NintendoSwitch/Framework/NintendoSwitch_SingleSwitchProgram.cpp \
    Source/NintendoSwitch/Framework/NintendoSwitch_SingleSwitchProgramWidget.cpp \
    Source/NintendoSwitch/Framework/NintendoSwitch_SwitchSystem.cpp \
    Source/NintendoSwitch/Framework/NintendoSwitch_SwitchSystemWidget.cpp \
    Source/NintendoSwitch/Framework/NintendoSwitch_VirtualController.cpp \
    Source/NintendoSwitch/Framework/NintendoSwitch_VirtualControllerMapping.cpp \
    Source/NintendoSwitch/Framework/NintendoSwitch_VirtualControllerState.cpp \
    Source/NintendoSwitch/InferenceTraining/PokemonHome_GenerateNameOCR.cpp \
    Source/NintendoSwitch/NintendoSwitch_Panels.cpp \
    Source/NintendoSwitch/NintendoSwitch_Settings.cpp \
    Source/NintendoSwitch/Options/GoHomeWhenDoneOption.cpp \
    Source/NintendoSwitch/Options/NintendoSwitch_FriendCodeListOption.cpp \
    Source/NintendoSwitch/Options/SwitchDateOption.cpp \
    Source/NintendoSwitch/Options/TimeExpressionOption.cpp \
    Source/NintendoSwitch/Programs/NintendoSwitch_FriendCodeAdder.cpp \
    Source/NintendoSwitch/Programs/NintendoSwitch_FriendDelete.cpp \
    Source/NintendoSwitch/Programs/NintendoSwitch_GameEntry.cpp \
    Source/NintendoSwitch/Programs/NintendoSwitch_PreventSleep.cpp \
    Source/NintendoSwitch/Programs/NintendoSwitch_SwitchViewer.cpp \
    Source/NintendoSwitch/Programs/NintendoSwitch_TurboA.cpp \
    Source/NintendoSwitch/Programs/NintendoSwitch_TurboButton.cpp \
    Source/NintendoSwitch/Programs/NintendoSwitch_VirtualConsole.cpp \
    Source/NintendoSwitch/Programs/PokemonHome_PageSwap.cpp \
    Source/NintendoSwitch/TestProgramComputer.cpp \
    Source/NintendoSwitch/TestProgramSwitch.cpp \
    Source/PanelLists.cpp \
    Source/Pokemon/Inference/Pokemon_BerryNameReader.cpp \
    Source/Pokemon/Inference/Pokemon_IVCheckerReader.cpp \
    Source/Pokemon/Inference/Pokemon_NameReader.cpp \
    Source/Pokemon/Inference/Pokemon_PokeballNameReader.cpp \
    Source/Pokemon/Inference/Pokemon_TrainIVCheckerOCR.cpp \
    Source/Pokemon/Inference/Pokemon_TrainPokemonOCR.cpp \
    Source/Pokemon/Options/Pokemon_BallSelectOption.cpp \
    Source/Pokemon/Options/Pokemon_BallSelectWidget.cpp \
    Source/Pokemon/Options/Pokemon_BerrySelectWidget.cpp \
    Source/Pokemon/Options/Pokemon_IVCheckerOption.cpp \
    Source/Pokemon/Options/Pokemon_IVCheckerWidget.cpp \
    Source/Pokemon/Options/Pokemon_NameListOption.cpp \
    Source/Pokemon/Options/Pokemon_NameSelectOption.cpp \
    Source/Pokemon/Options/Pokemon_NameSelectWidget.cpp \
    Source/Pokemon/Pokemon_EncounterStats.cpp \
    Source/Pokemon/Pokemon_IVChecker.cpp \
    Source/Pokemon/Pokemon_Notification.cpp \
    Source/Pokemon/Pokemon_ShinySparkleSet.cpp \
    Source/Pokemon/Pokemon_Types.cpp \
    Source/Pokemon/Resources/Pokemon_BerryNames.cpp \
    Source/Pokemon/Resources/Pokemon_BerrySprites.cpp \
    Source/Pokemon/Resources/Pokemon_PokeballNames.cpp \
    Source/Pokemon/Resources/Pokemon_PokemonNames.cpp \
    Source/Pokemon/Resources/Pokemon_PokemonSlugs.cpp \
    Source/PokemonBDSP/Inference/Battles/PokemonBDSP_BattleBallReader.cpp \
    Source/PokemonBDSP/Inference/Battles/PokemonBDSP_BattleMenuDetector.cpp \
    Source/PokemonBDSP/Inference/Battles/PokemonBDSP_EndBattleDetector.cpp \
    Source/PokemonBDSP/Inference/Battles/PokemonBDSP_ExperienceGainDetector.cpp \
    Source/PokemonBDSP/Inference/Battles/PokemonBDSP_StartBattleDetector.cpp \
    Source/PokemonBDSP/Inference/BoxSystem/PokemonBDSP_BoxDetector.cpp \
    Source/PokemonBDSP/Inference/BoxSystem/PokemonBDSP_BoxShinyDetector.cpp \
    Source/PokemonBDSP/Inference/BoxSystem/PokemonBDSP_IVCheckerReader.cpp \
    Source/PokemonBDSP/Inference/PokemonBDSP_DialogDetector.cpp \
    Source/PokemonBDSP/Inference/PokemonBDSP_MapDetector.cpp \
    Source/PokemonBDSP/Inference/PokemonBDSP_MarkFinder.cpp \
    Source/PokemonBDSP/Inference/PokemonBDSP_MenuDetector.cpp \
    Source/PokemonBDSP/Inference/PokemonBDSP_PokeballSpriteMatcher.cpp \
    Source/PokemonBDSP/Inference/PokemonBDSP_ReceivePokemonDetector.cpp \
    Source/PokemonBDSP/Inference/PokemonBDSP_SelectionArrow.cpp \
    Source/PokemonBDSP/Inference/PokemonBDSP_VSSeekerReaction.cpp \
    Source/PokemonBDSP/Inference/ShinyDetection/PokemonBDSP_ShinyEncounterDetector.cpp \
    Source/PokemonBDSP/Inference/ShinyDetection/PokemonBDSP_ShinySparkleSet.cpp \
    Source/PokemonBDSP/Options/EncounterFilter/PokemonBDSP_EncounterFilterEnums.cpp \
    Source/PokemonBDSP/Options/EncounterFilter/PokemonBDSP_EncounterFilterOption.cpp \
    Source/PokemonBDSP/Options/EncounterFilter/PokemonBDSP_EncounterFilterOverride.cpp \
    Source/PokemonBDSP/Options/EncounterFilter/PokemonBDSP_EncounterFilterWidget.cpp \
    Source/PokemonBDSP/Options/PokemonBDSP_BerrySelector.cpp \
    Source/PokemonBDSP/Options/PokemonBDSP_EggHatchFilter.cpp \
    Source/PokemonBDSP/Options/PokemonBDSP_ShortcutDirection.cpp \
    Source/PokemonBDSP/Panels_PokemonBDSP.cpp \
    Source/PokemonBDSP/PokemonBDSP_Settings.cpp \
    Source/PokemonBDSP/Programs/Eggs/PokemonBDSP_EggAutonomous.cpp \
    Source/PokemonBDSP/Programs/Eggs/PokemonBDSP_EggAutonomousState.cpp \
    Source/PokemonBDSP/Programs/Eggs/PokemonBDSP_EggFeedback.cpp \
    Source/PokemonBDSP/Programs/Eggs/PokemonBDSP_EggFetcher.cpp \
    Source/PokemonBDSP/Programs/Eggs/PokemonBDSP_EggHatcher.cpp \
    Source/PokemonBDSP/Programs/Eggs/PokemonBDSP_EggRoutines.cpp \
    Source/PokemonBDSP/Programs/Farming/PokemonBDSP_AmitySquarePickUpFarmer.cpp \
    Source/PokemonBDSP/Programs/Farming/PokemonBDSP_DoublesLeveling.cpp \
    Source/PokemonBDSP/Programs/Farming/PokemonBDSP_GiftBerryReset.cpp \
    Source/PokemonBDSP/Programs/Farming/PokemonBDSP_MoneyFarmerRoute210.cpp \
    Source/PokemonBDSP/Programs/Farming/PokemonBDSP_MoneyFarmerRoute212.cpp \
    Source/PokemonBDSP/Programs/General/PokemonBDSP_AutonomousBallThrower.cpp \
    Source/PokemonBDSP/Programs/General/PokemonBDSP_MassRelease.cpp \
    Source/PokemonBDSP/Programs/Glitches/PokemonBDSP_ActivateMenuGlitch-1.1.3.cpp \
    Source/PokemonBDSP/Programs/Glitches/PokemonBDSP_ActivateMenuGlitch-1.1.2.cpp \
    Source/PokemonBDSP/Programs/Glitches/PokemonBDSP_CloneItemsBoxCopy.cpp \
    Source/PokemonBDSP/Programs/Glitches/PokemonBDSP_CloneItemsBoxCopy2.cpp \
    Source/PokemonBDSP/Programs/Glitches/PokemonBDSP_CloneItemsMenuOverlap.cpp \
    Source/PokemonBDSP/Programs/Glitches/PokemonBDSP_MenuOverlap.cpp \
    Source/PokemonBDSP/Programs/PokemonBDSP_BasicCatcher.cpp \
    Source/PokemonBDSP/Programs/PokemonBDSP_BoxRelease.cpp \
    Source/PokemonBDSP/Programs/PokemonBDSP_EncounterDetection.cpp \
    Source/PokemonBDSP/Programs/PokemonBDSP_EncounterHandler.cpp \
    Source/PokemonBDSP/Programs/PokemonBDSP_GameEntry.cpp \
    Source/PokemonBDSP/Programs/PokemonBDSP_GameNavigation.cpp \
    Source/PokemonBDSP/Programs/PokemonBDSP_GlobalRoomHeal.cpp \
    Source/PokemonBDSP/Programs/PokemonBDSP_OverworldTrigger.cpp \
    Source/PokemonBDSP/Programs/PokemonBDSP_RunFromBattle.cpp \
    Source/PokemonBDSP/Programs/ShinyHunting/PokemonBDSP_LegendaryReset.cpp \
    Source/PokemonBDSP/Programs/ShinyHunting/PokemonBDSP_ShinyHunt-Fishing.cpp \
    Source/PokemonBDSP/Programs/ShinyHunting/PokemonBDSP_ShinyHunt-Overworld.cpp \
    Source/PokemonBDSP/Programs/ShinyHunting/PokemonBDSP_ShinyHunt-Shaymin.cpp \
    Source/PokemonBDSP/Programs/ShinyHunting/PokemonBDSP_StarterReset.cpp \
    Source/PokemonBDSP/Programs/Trading/PokemonBDSP_SelfBoxTrade.cpp \
    Source/PokemonBDSP/Programs/Trading/PokemonBDSP_SelfTouchTrade.cpp \
    Source/PokemonBDSP/Programs/Trading/PokemonBDSP_TradeRoutines.cpp \
    Source/PokemonLA/Inference/Battles/PokemonLA_BattleMenuDetector.cpp \
    Source/PokemonLA/Inference/Battles/PokemonLA_BattleMoveSelectionDetector.cpp \
    Source/PokemonLA/Inference/Battles/PokemonLA_BattlePokemonSwitchDetector.cpp \
    Source/PokemonLA/Inference/Objects/PokemonLA_ArcDetector.cpp \
    Source/PokemonLA/Inference/Objects/PokemonLA_ArcPhoneDetector.cpp \
    Source/PokemonLA/Inference/Objects/PokemonLA_BubbleDetector.cpp \
    Source/PokemonLA/Inference/Objects/PokemonLA_ButtonDetector.cpp \
    Source/PokemonLA/Inference/Objects/PokemonLA_DialogueEllipseDetector.cpp \
    Source/PokemonLA/Inference/Objects/PokemonLA_FlagDetector.cpp \
    Source/PokemonLA/Inference/Objects/PokemonLA_FlagTracker.cpp \
    Source/PokemonLA/Inference/Objects/PokemonLA_QuestMarkDetector.cpp \
    Source/PokemonLA/Inference/Objects/PokemonLA_ShinySymbolDetector.cpp \
    Source/PokemonLA/Inference/Objects/PokemonLA_WhiteObjectDetector.cpp \
    Source/PokemonLA/Inference/PokemonLA_CommonColorCheck.cpp \
    Source/PokemonLA/Inference/PokemonLA_DialogDetector.cpp \
    Source/PokemonLA/Inference/PokemonLA_ItemCompatibilityDetector.cpp \
    Source/PokemonLA/Inference/PokemonLA_MapDetector.cpp \
    Source/PokemonLA/Inference/PokemonLA_MountDetector.cpp \
    Source/PokemonLA/Inference/PokemonLA_NotificationReader.cpp \
    Source/PokemonLA/Inference/PokemonLA_OutbreakReader.cpp \
    Source/PokemonLA/Inference/PokemonLA_SelectedRegionDetector.cpp \
    Source/PokemonLA/Inference/PokemonLA_StatusInfoScreenDetector.cpp \
    Source/PokemonLA/Inference/PokemonLA_UnderAttackDetector.cpp \
    Source/PokemonLA/Inference/Sounds/PokemonLA_AlphaMusicDetector.cpp \
    Source/PokemonLA/Inference/Sounds/PokemonLA_AlphaRoarDetector.cpp \
    Source/PokemonLA/Inference/Sounds/PokemonLA_ShinySoundDetector.cpp \
    Source/PokemonLA/Options/PokemonLA_BattlePokemonActionTable.cpp \
    Source/PokemonLA/Options/PokemonLA_CustomPathTable.cpp \
    Source/PokemonLA/Options/PokemonLA_ShinyDetectedAction.cpp \
    Source/PokemonLA/Options/PokemonLA_TradeCountTable.cpp \
    Source/PokemonLA/Options/PokemonLA_TravelLocation.cpp \
    Source/PokemonLA/Panels_PokemonLA.cpp \
    Source/PokemonLA/PokemonLA_Locations.cpp \
    Source/PokemonLA/PokemonLA_Settings.cpp \
    Source/PokemonLA/PokemonLA_TravelLocations.cpp \
    Source/PokemonLA/Programs/Farming/PokemonLA_MagikarpMoveGrinder.cpp \
    Source/PokemonLA/Programs/Farming/PokemonLA_TenacityCandyFarmer.cpp \
    Source/PokemonLA/Programs/General/PokemonLA_ClothingBuyer.cpp \
    Source/PokemonLA/Programs/General/PokemonLA_SkipToFullMoon.cpp \
    Source/PokemonLA/Programs/PokemonLA_BattleRoutines.cpp \
    Source/PokemonLA/Programs/PokemonLA_BraviaryHeightGlitch.cpp \
    Source/PokemonLA/Programs/PokemonLA_DistortionWaiter.cpp \
    Source/PokemonLA/Programs/PokemonLA_EscapeFromAttack.cpp \
    Source/PokemonLA/Programs/PokemonLA_FlagNavigationAir.cpp \
    Source/PokemonLA/Programs/PokemonLA_GameEntry.cpp \
    Source/PokemonLA/Programs/PokemonLA_MountChange.cpp \
    Source/PokemonLA/Programs/PokemonLA_OutbreakFinder.cpp \
    Source/PokemonLA/Programs/PokemonLA_RegionNavigation.cpp \
    Source/PokemonLA/Programs/ShinyHunting/PokemonLA_PostMMOSpawnReset.cpp \
    Source/PokemonLA/Programs/ShinyHunting/PokemonLA_ShinyHunt-CustomPath.cpp \
    Source/PokemonLA/Programs/TestPrograms/PokemonLA_AlphaMusicListener.cpp \
    Source/PokemonLA/Programs/TestPrograms/PokemonLA_AlphaRoarListener.cpp \
    Source/PokemonLA/Programs/TestPrograms/PokemonLA_MountDetectionTest.cpp \
    Source/PokemonLA/Programs/Trading/PokemonLA_SelfBoxTrade.cpp \
    Source/PokemonLA/Programs/Trading/PokemonLA_SelfTouchTrade.cpp \
    Source/PokemonLA/Programs/Trading/PokemonLA_TradeRoutines.cpp \
    Source/PokemonLA/Programs/Farming/PokemonLA_NuggetFarmerHighlands.cpp \
    Source/PokemonLA/Programs/Farming/PokemonLA_IngoBattleGrinder.cpp \
    Source/PokemonLA/Programs/ShinyHunting/PokemonLA_CrobatFinder.cpp \
    Source/PokemonLA/Programs/ShinyHunting/PokemonLA_GalladeFinder.cpp \
    Source/PokemonLA/Programs/ShinyHunting/PokemonLA_FroslassFinder.cpp \
    Source/PokemonLA/Programs/ShinyHunting/PokemonLA_TreeShinyHunting.cpp \
    Source/PokemonLA/Programs/ShinyHunting/PokemonLA_UnownFinder.cpp \
    Source/PokemonLA/Programs/ShinyHunting/PokemonLA_ShinyHunt-FlagPin.cpp \
    Source/PokemonLA/Programs/ShinyHunting/PokemonLA_ShinyHunt-LakeTrio.cpp \
    Source/PokemonLA/Programs/TestPrograms/PokemonLA_OverworldWatcher.cpp \
    Source/PokemonLA/Programs/TestPrograms/PokemonLA_ShinySoundListener.cpp \
    Source/PokemonLA/Programs/TestPrograms/PokemonLA_FlagNavigationTest.cpp \
    Source/PokemonLA/Resources/PokemonLA_AvailablePokemon.cpp \
    Source/PokemonLA/Resources/PokemonLA_PokemonIcons.cpp \
    Source/PokemonSwSh/Commands/PokemonSwSh_Commands_AutoHosts.cpp \
    Source/PokemonSwSh/Commands/PokemonSwSh_Commands_DateSpam.cpp \
    Source/PokemonSwSh/Commands/PokemonSwSh_Commands_DaySkippers.cpp \
    Source/PokemonSwSh/Commands/PokemonSwSh_Commands_EggRoutines.cpp \
    Source/PokemonSwSh/Commands/PokemonSwSh_Commands_GameEntry.cpp \
    Source/PokemonSwSh/Commands/PokemonSwSh_Commands_Misc.cpp \
    Source/PokemonSwSh/Inference/Battles/PokemonSwSh_BattleBallReader.cpp \
    Source/PokemonSwSh/Inference/Battles/PokemonSwSh_BattleDialogDetector.cpp \
    Source/PokemonSwSh/Inference/Battles/PokemonSwSh_BattleDialogTracker.cpp \
    Source/PokemonSwSh/Inference/Battles/PokemonSwSh_BattleMenuDetector.cpp \
    Source/PokemonSwSh/Inference/Battles/PokemonSwSh_ExperienceGainDetector.cpp \
    Source/PokemonSwSh/Inference/Battles/PokemonSwSh_StartBattleDetector.cpp \
    Source/PokemonSwSh/Inference/Dens/PokemonSwSh_BeamSetter.cpp \
    Source/PokemonSwSh/Inference/Dens/PokemonSwSh_DenMonReader.cpp \
    Source/PokemonSwSh/Inference/Dens/PokemonSwSh_RaidCatchDetector.cpp \
    Source/PokemonSwSh/Inference/Dens/PokemonSwSh_RaidLobbyReader.cpp \
    Source/PokemonSwSh/Inference/PokemonSwSh_FishingDetector.cpp \
    Source/PokemonSwSh/Inference/PokemonSwSh_IVCheckerReader.cpp \
    Source/PokemonSwSh/Inference/PokemonSwSh_MarkFinder.cpp \
    Source/PokemonSwSh/Inference/PokemonSwSh_PokemonSpriteReader.cpp \
    Source/PokemonSwSh/Inference/PokemonSwSh_PromptDetector.cpp \
    Source/PokemonSwSh/Inference/PokemonSwSh_QuantityReader.cpp \
    Source/PokemonSwSh/Inference/PokemonSwSh_ReceivePokemonDetector.cpp \
    Source/PokemonSwSh/Inference/PokemonSwSh_SelectionArrowFinder.cpp \
    Source/PokemonSwSh/Inference/PokemonSwSh_SummaryShinySymbolDetector.cpp \
    Source/PokemonSwSh/Inference/PokemonSwSh_TypeSymbolFinder.cpp \
    Source/PokemonSwSh/Inference/PokemonSwSh_YCommDetector.cpp \
    Source/PokemonSwSh/Inference/ShinyDetection/PokemonSwSh_ShinyEncounterDetector.cpp \
    Source/PokemonSwSh/Inference/ShinyDetection/PokemonSwSh_ShinySparkleSet.cpp \
    Source/PokemonSwSh/Inference/ShinyDetection/PokemonSwSh_SparkleDetectorRadial.cpp \
    Source/PokemonSwSh/Inference/ShinyDetection/PokemonSwSh_SparkleDetectorSquare.cpp \
    Source/PokemonSwSh/InferenceTraining/PokemonSwSh_GenerateIVCheckerOCR.cpp \
    Source/PokemonSwSh/InferenceTraining/PokemonSwSh_GenerateNameOCRPokedex.cpp \
    Source/PokemonSwSh/MaxLair/AI/PokemonSwSh_MaxLair_AI.cpp \
    Source/PokemonSwSh/MaxLair/AI/PokemonSwSh_MaxLair_AI_PathMatchup.cpp \
    Source/PokemonSwSh/MaxLair/AI/PokemonSwSh_MaxLair_AI_RentalBossMatchup.cpp \
    Source/PokemonSwSh/MaxLair/AI/PokemonSwSh_MaxLair_AI_Tools.cpp \
    Source/PokemonSwSh/MaxLair/Framework/PokemonSwSh_MaxLair_CatchScreenTracker.cpp \
    Source/PokemonSwSh/MaxLair/Inference/PokemonSwSh_MaxLair_Detect_PathMap.cpp \
    Source/PokemonSwSh/MaxLair/Inference/PokemonSwSh_MaxLair_Detect_PathSide.cpp \
    Source/PokemonSwSh/MaxLair/Inference/PokemonSwSh_MaxLair_Detect_ProfessorSwap.cpp \
    Source/PokemonSwSh/MaxLair/Options/PokemonSwSh_MaxLair_Options.cpp \
    Source/PokemonSwSh/MaxLair/Options/PokemonSwSh_MaxLair_Options_BossAction.cpp \
    Source/PokemonSwSh/MaxLair/Options/PokemonSwSh_MaxLair_Options_Consoles.cpp \
    Source/PokemonSwSh/MaxLair/Options/PokemonSwSh_MaxLair_Options_Hosting.cpp \
    Source/PokemonSwSh/MaxLair/PokemonSwSh_MaxLair_BossFinder.cpp \
    Source/PokemonSwSh/MaxLair/PokemonSwSh_MaxLair_StrongBoss.cpp \
    Source/PokemonSwSh/MaxLair/Program/PokemonSwSh_MaxLair_Run_Adventure.cpp \
    Source/PokemonSwSh/MaxLair/Program/PokemonSwSh_MaxLair_Run_EnterLobby.cpp \
    Source/PokemonSwSh/MaxLair/Program/PokemonSwSh_MaxLair_Run_ProfessorSwap.cpp \
    Source/PokemonSwSh/MaxLair/Program/PokemonSwSh_MaxLair_Run_StartSolo.cpp \
    Source/PokemonSwSh/Options/EncounterFilter/PokemonSwSh_EncounterFilterEnums.cpp \
    Source/PokemonSwSh/Options/EncounterFilter/PokemonSwSh_EncounterFilterOption.cpp \
    Source/PokemonSwSh/Options/EncounterFilter/PokemonSwSh_EncounterFilterOverride.cpp \
    Source/PokemonSwSh/Options/EncounterFilter/PokemonSwSh_EncounterFilterWidget.cpp \
    Source/PokemonSwSh/Options/PokemonSwSh_AutoHostNotification.cpp \
    Source/PokemonSwSh/Options/PokemonSwSh_Catchability.cpp \
    Source/PokemonSwSh/Options/PokemonSwSh_DateToucher.cpp \
    Source/PokemonSwSh/Options/PokemonSwSh_EggStepCount.cpp \
    Source/PokemonSwSh/Options/PokemonSwSh_FossilTable.cpp \
    Source/PokemonSwSh/Options/PokemonSwSh_MultiHostTable.cpp \
    Source/PokemonSwSh/Options/PokemonSwSh_RegiSelector.cpp \
    Source/PokemonSwSh/PkmnLib/PokemonSwSh_PkmnLib_Battle.cpp \
    Source/PokemonSwSh/PkmnLib/PokemonSwSh_PkmnLib_Field.cpp \
    Source/PokemonSwSh/PkmnLib/PokemonSwSh_PkmnLib_Matchup.cpp \
    Source/PokemonSwSh/PkmnLib/PokemonSwSh_PkmnLib_Moves.cpp \
    Source/PokemonSwSh/PkmnLib/PokemonSwSh_PkmnLib_Pokemon.cpp \
    Source/PokemonSwSh/PkmnLib/PokemonSwSh_PkmnLib_Stats.cpp \
    Source/PokemonSwSh/PkmnLib/PokemonSwSh_PkmnLib_Types.cpp \
    Source/PokemonSwSh/PokemonSwSh_Panels.cpp \
    Source/PokemonSwSh/PokemonSwSh_Settings.cpp \
    Source/PokemonSwSh/Programs/DateSpamFarmers/PokemonSwSh_DateSpam-PokeJobsFarmer.cpp \
    Source/PokemonSwSh/Programs/EggPrograms/PokemonSwSh_EggFetcherMultiple.cpp \
    Source/PokemonSwSh/Programs/General/PokemonSwSh_AutonomousBallThrower.cpp \
    Source/PokemonSwSh/Programs/General/PokemonSwSh_BallThrower.cpp \
    Source/PokemonSwSh/Programs/General/PokemonSwSh_BoxReorderNationalDex.cpp \
    Source/PokemonSwSh/Programs/General/PokemonSwSh_ClothingBuyer.cpp \
    Source/PokemonSwSh/Programs/General/PokemonSwSh_DexRecFinder.cpp \
    Source/PokemonSwSh/Programs/General/PokemonSwSh_MassRelease.cpp \
    Source/PokemonSwSh/Programs/General/PokemonSwSh_SurpriseTrade.cpp \
    Source/PokemonSwSh/Programs/General/PokemonSwSh_TradeBot.cpp \
    Source/PokemonSwSh/Programs/Hosting/PokemonSwSh_AutoHost.cpp \
    Source/PokemonSwSh/Programs/Hosting/PokemonSwSh_AutoHostStats.cpp \
    Source/PokemonSwSh/MaxLair/AI/PokemonSwSh_MaxLair_AI_SelectItem.cpp \
    Source/PokemonSwSh/MaxLair/AI/PokemonSwSh_MaxLair_AI_SelectMove.cpp \
    Source/PokemonSwSh/MaxLair/AI/PokemonSwSh_MaxLair_AI_SelectPath.cpp \
    Source/PokemonSwSh/MaxLair/AI/PokemonSwSh_MaxLair_AI_SelectStarter.cpp \
    Source/PokemonSwSh/MaxLair/AI/PokemonSwSh_MaxLair_AI_SwapCatch.cpp \
    Source/PokemonSwSh/MaxLair/AI/PokemonSwSh_MaxLair_AI_SwapProfessor.cpp \
    Source/PokemonSwSh/MaxLair/Framework/PokemonSwSh_MaxLair_Notifications.cpp \
    Source/PokemonSwSh/MaxLair/Framework/PokemonSwSh_MaxLair_State.cpp \
    Source/PokemonSwSh/MaxLair/Framework/PokemonSwSh_MaxLair_StateMachine.cpp \
    Source/PokemonSwSh/MaxLair/Framework/PokemonSwSh_MaxLair_StateTracker.cpp \
    Source/PokemonSwSh/MaxLair/Inference/PokemonSwSh_MaxLair_Detect_BattleMenu.cpp \
    Source/PokemonSwSh/MaxLair/Inference/PokemonSwSh_MaxLair_Detect_EndBattle.cpp \
    Source/PokemonSwSh/MaxLair/Inference/PokemonSwSh_MaxLair_Detect_Entrance.cpp \
    Source/PokemonSwSh/MaxLair/Inference/PokemonSwSh_MaxLair_Detect_HPPP.cpp \
    Source/PokemonSwSh/MaxLair/Inference/PokemonSwSh_MaxLair_Detect_ItemSelectMenu.cpp \
    Source/PokemonSwSh/MaxLair/Inference/PokemonSwSh_MaxLair_Detect_Lobby.cpp \
    Source/PokemonSwSh/MaxLair/Inference/PokemonSwSh_MaxLair_Detect_PathSelect.cpp \
    Source/PokemonSwSh/MaxLair/Inference/PokemonSwSh_MaxLair_Detect_PokemonReader.cpp \
    Source/PokemonSwSh/MaxLair/Inference/PokemonSwSh_MaxLair_Detect_PokemonSelectMenu.cpp \
    Source/PokemonSwSh/MaxLair/Inference/PokemonSwSh_MaxLair_Detect_PokemonSwapMenu.cpp \
    Source/PokemonSwSh/MaxLair/PokemonSwSh_MaxLair_Standard.cpp \
    Source/PokemonSwSh/MaxLair/Program/PokemonSwSh_MaxLair_Run_Battle.cpp \
    Source/PokemonSwSh/MaxLair/Program/PokemonSwSh_MaxLair_Run_CaughtScreen.cpp \
    Source/PokemonSwSh/MaxLair/Program/PokemonSwSh_MaxLair_Run_Entrance.cpp \
    Source/PokemonSwSh/MaxLair/Program/PokemonSwSh_MaxLair_Run_ItemSelect.cpp \
    Source/PokemonSwSh/MaxLair/Program/PokemonSwSh_MaxLair_Run_PathSelect.cpp \
    Source/PokemonSwSh/MaxLair/Program/PokemonSwSh_MaxLair_Run_PokemonSelect.cpp \
    Source/PokemonSwSh/MaxLair/Program/PokemonSwSh_MaxLair_Run_PokemonSwap.cpp \
    Source/PokemonSwSh/MaxLair/Program/PokemonSwSh_MaxLair_Run_Start.cpp \
    Source/PokemonSwSh/Programs/Hosting/PokemonSwSh_DenTools.cpp \
    Source/PokemonSwSh/Programs/NonShinyHunting/PokemonSwSh_StatsReset-Calyrex.cpp \
    Source/PokemonSwSh/Programs/NonShinyHunting/PokemonSwSh_StatsReset-Moltres.cpp \
    Source/PokemonSwSh/Programs/NonShinyHunting/PokemonSwSh_StatsReset-Regi.cpp \
    Source/PokemonSwSh/Programs/NonShinyHunting/PokemonSwSh_StatsReset.cpp \
    Source/PokemonSwSh/Programs/OverworldBot/PokemonSwSh_OverworldMovement.cpp \
    Source/PokemonSwSh/Programs/OverworldBot/PokemonSwSh_OverworldTargetTracker.cpp \
    Source/PokemonSwSh/Programs/OverworldBot/PokemonSwSh_OverworldTrajectory.cpp \
    Source/PokemonSwSh/Programs/OverworldBot/PokemonSwSh_OverworldTrigger.cpp \
    Source/PokemonSwSh/Programs/OverworldBot/PokemonSwSh_ShinyHuntAutonomous-Overworld.cpp \
    Source/PokemonSwSh/Programs/PokemonSwSh_BasicCatcher.cpp \
    Source/PokemonSwSh/Programs/PokemonSwSh_EncounterDetection.cpp \
    Source/PokemonSwSh/Programs/PokemonSwSh_EncounterHandler.cpp \
    Source/PokemonSwSh/Programs/PokemonSwSh_Internet.cpp \
    Source/PokemonSwSh/Programs/PokemonSwSh_StartGame.cpp \
    Source/PokemonSwSh/Programs/ShinyHuntAutonomous/PokemonSwSh_ShinyHuntAutonomous-BerryTree.cpp \
    Source/PokemonSwSh/Programs/ShinyHuntAutonomous/PokemonSwSh_ShinyHuntAutonomous-Fishing.cpp \
    Source/PokemonSwSh/Programs/ShinyHuntAutonomous/PokemonSwSh_ShinyHuntAutonomous-IoATrade.cpp \
    Source/PokemonSwSh/Programs/ShinyHuntAutonomous/PokemonSwSh_ShinyHuntAutonomous-Regi.cpp \
    Source/PokemonSwSh/Programs/ShinyHuntAutonomous/PokemonSwSh_ShinyHuntAutonomous-Regigigas2.cpp \
    Source/PokemonSwSh/Programs/ShinyHuntAutonomous/PokemonSwSh_ShinyHuntAutonomous-StrongSpawn.cpp \
    Source/PokemonSwSh/Programs/ShinyHuntAutonomous/PokemonSwSh_ShinyHuntAutonomous-SwordsOfJustice.cpp \
    Source/PokemonSwSh/Programs/ShinyHuntAutonomous/PokemonSwSh_ShinyHuntAutonomous-Whistling.cpp \
    Source/PokemonSwSh/Programs/ShinyHuntUnattended/PokemonSwSh_CurryHunter.cpp \
    Source/PokemonSwSh/Programs/ShinyHuntUnattended/PokemonSwSh_MultiGameFossil.cpp \
    Source/PokemonSwSh/Programs/ShinyHuntUnattended/PokemonSwSh_ShinyHunt-Regi.cpp \
    Source/PokemonSwSh/Programs/ShinyHuntUnattended/PokemonSwSh_ShinyHuntTools.cpp \
    Source/PokemonSwSh/Programs/ShinyHuntUnattended/PokemonSwSh_ShinyHuntUnattended-IoATrade.cpp \
    Source/PokemonSwSh/Programs/ShinyHuntUnattended/PokemonSwSh_ShinyHuntUnattended-Regi.cpp \
    Source/PokemonSwSh/Programs/ShinyHuntUnattended/PokemonSwSh_ShinyHuntUnattended-Regigigas2.cpp \
    Source/PokemonSwSh/Programs/ShinyHuntUnattended/PokemonSwSh_ShinyHuntUnattended-StrongSpawn.cpp \
    Source/PokemonSwSh/Programs/ShinyHuntUnattended/PokemonSwSh_ShinyHuntUnattended-SwordsOfJustice.cpp \
    Source/PokemonSwSh/Programs/DateSpamFarmers/PokemonSwSh_DateSpam-BerryFarmer.cpp \
    Source/PokemonSwSh/Programs/DateSpamFarmers/PokemonSwSh_DateSpam-DailyHighlightFarmer.cpp \
    Source/PokemonSwSh/Programs/DateSpamFarmers/PokemonSwSh_DateSpam-LotoFarmer.cpp \
    Source/PokemonSwSh/Programs/DateSpamFarmers/PokemonSwSh_DateSpam-StowOnSideFarmer.cpp \
    Source/PokemonSwSh/Programs/DateSpamFarmers/PokemonSwSh_DateSpam-WattFarmer.cpp \
    Source/PokemonSwSh/Programs/DenHunting/PokemonSwSh_BeamReset.cpp \
    Source/PokemonSwSh/Programs/DenHunting/PokemonSwSh_DaySkipperEU.cpp \
    Source/PokemonSwSh/Programs/DenHunting/PokemonSwSh_DaySkipperJPN-7.8k.cpp \
    Source/PokemonSwSh/Programs/DenHunting/PokemonSwSh_DaySkipperJPN.cpp \
    Source/PokemonSwSh/Programs/DenHunting/PokemonSwSh_DaySkipperUS.cpp \
    Source/PokemonSwSh/Programs/DenHunting/PokemonSwSh_EventBeamFinder.cpp \
    Source/PokemonSwSh/Programs/DenHunting/PokemonSwSh_PurpleBeamFinder.cpp \
    Source/PokemonSwSh/Programs/EggPrograms/PokemonSwSh_EggCombined2.cpp \
    Source/PokemonSwSh/Programs/EggPrograms/PokemonSwSh_EggFetcher2.cpp \
    Source/PokemonSwSh/Programs/EggPrograms/PokemonSwSh_EggHatcher.cpp \
    Source/PokemonSwSh/Programs/EggPrograms/PokemonSwSh_EggSuperCombined2.cpp \
    Source/PokemonSwSh/Programs/EggPrograms/PokemonSwSh_GodEggDuplication.cpp \
    Source/PokemonSwSh/Programs/EggPrograms/PokemonSwSh_GodEggItemDupe.cpp \
    Source/PokemonSwSh/Programs/Hosting/PokemonSwSh_AutoHost-MultiGame.cpp \
    Source/PokemonSwSh/Programs/Hosting/PokemonSwSh_AutoHost-Rolling.cpp \
    Source/PokemonSwSh/Programs/Hosting/PokemonSwSh_DenRoller.cpp \
    Source/PokemonSwSh/Programs/PokemonSwSh_RaidItemFarmerOKHO.cpp \
    Source/PokemonSwSh/Programs/PokemonSwSh_SynchronizedSpinning.cpp \
    Source/PokemonSwSh/Programs/QoLMacros/PokemonSwSh_FastCodeEntry.cpp \
    Source/PokemonSwSh/Programs/QoLMacros/PokemonSwSh_FriendSearchDisconnect.cpp \
    Source/PokemonSwSh/Resources/PokemonSwSh_MaxLairDatabase.cpp \
    Source/PokemonSwSh/Resources/PokemonSwSh_PokeballSprites.cpp \
    Source/PokemonSwSh/Resources/PokemonSwSh_PokemonIcons.cpp \
    Source/PokemonSwSh/Resources/PokemonSwSh_PokemonSprites.cpp \
    Source/PokemonSwSh/Resources/PokemonSwSh_TypeMatchup.cpp \
    Source/PokemonSwSh/Resources/PokemonSwSh_TypeSprites.cpp \
    Source/PokemonSwSh/ShinyHuntTracker.cpp

HEADERS += \
    ../ClientSource/Connection/BotBase.h \
    ../ClientSource/Connection/BotBaseMessage.h \
    ../ClientSource/Connection/MessageLogger.h \
    ../ClientSource/Connection/MessageSniffer.h \
    ../ClientSource/Connection/PABotBase.h \
    ../ClientSource/Connection/PABotBaseConnection.h \
    ../ClientSource/Connection/SerialConnection.h \
    ../ClientSource/Connection/SerialConnectionPOSIX.h \
    ../ClientSource/Connection/SerialConnectionWinAPI.h \
    ../ClientSource/Connection/StreamInterface.h \
    ../ClientSource/Libraries/Logging.h \
    ../ClientSource/Libraries/MessageConverter.h \
    ../Common/CRC32.h \
    ../Common/Compiler.h \
    ../Common/Cpp/AbstractLogger.h \
    ../Common/Cpp/AlignedVector.h \
    ../Common/Cpp/AlignedVector.tpp \
    ../Common/Cpp/AsyncDispatcher.h \
    ../Common/Cpp/CancellableScope.h \
    ../Common/Cpp/Color.h \
    ../Common/Cpp/CpuId.h \
    ../Common/Cpp/Exceptions.h \
    ../Common/Cpp/FireForgetDispatcher.h \
    ../Common/Cpp/FixedLimitVector.h \
    ../Common/Cpp/FixedLimitVector.tpp \
    ../Common/Cpp/LifetimeSanitizer.h \
    ../Common/Cpp/PanicDump.h \
    ../Common/Cpp/ParallelTaskRunner.h \
    ../Common/Cpp/PeriodicScheduler.h \
    ../Common/Cpp/PrettyPrint.h \
    ../Common/Cpp/SIMDDebuggers.h \
    ../Common/Cpp/SpinLock.h \
    ../Common/Cpp/Time.h \
    ../Common/Cpp/Unicode.h \
    ../Common/Microcontroller/DeviceRoutines.h \
    ../Common/Microcontroller/MessageProtocol.h \
    ../Common/NintendoSwitch/NintendoSwitch_Protocol_DigitEntry.h \
    ../Common/NintendoSwitch/NintendoSwitch_Protocol_PushButtons.h \
    ../Common/NintendoSwitch/NintendoSwitch_Protocol_PushButtons.h \
    ../Common/NintendoSwitch/NintendoSwitch_Protocol_Routines.h \
    ../Common/NintendoSwitch/NintendoSwitch_Tools.h \
    ../Common/PokemonSwSh/PokemonProgramIDs.h \
    ../Common/PokemonSwSh/PokemonSwSh_Protocol_AutoHosts.h \
    ../Common/PokemonSwSh/PokemonSwSh_Protocol_DateSpam.h \
    ../Common/PokemonSwSh/PokemonSwSh_Protocol_DaySkippers.h \
    ../Common/PokemonSwSh/PokemonSwSh_Protocol_EggRoutines.h \
    ../Common/PokemonSwSh/PokemonSwSh_Protocol_GameEntry.h \
    ../Common/PokemonSwSh/PokemonSwSh_Protocol_Misc.h \
    ../Common/Qt/AutoHeightTable.h \
    ../Common/Qt/AutoWidthLineEdit.h \
    ../Common/Qt/CodeValidator.h \
    ../Common/Qt/CollapsibleGroupBox.h \
    ../Common/Qt/ExpressionEvaluator.h \
    ../Common/Qt/ImageOpener.h \
    ../Common/Qt/NoWheelComboBox.h \
    ../Common/Qt/Options/BooleanCheckBox/BooleanCheckBoxBaseOption.h \
    ../Common/Qt/Options/BooleanCheckBox/BooleanCheckBoxBaseWidget.h \
    ../Common/Qt/Options/EditableTable/EditableTableBaseOption.h \
    ../Common/Qt/Options/EditableTable/EditableTableBaseWidget.h \
    ../Common/Qt/Options/FloatingPoint/FloatingPointBaseOption.h \
    ../Common/Qt/Options/FloatingPoint/FloatingPointBaseWidget.h \
    ../Common/Qt/Options/FossilTableBaseOption.h \
    ../Common/Qt/Options/MultiHostTableBaseOption.h \
    ../Common/Qt/Options/SimpleInteger/SimpleIntegerBaseOption.h \
    ../Common/Qt/Options/SimpleInteger/SimpleIntegerBaseWidget.h \
    ../Common/Qt/Options/String/StringBaseOption.h \
    ../Common/Qt/Options/String/StringBaseWidget.h \
    ../Common/Qt/Options/SwitchDate/SwitchDateBaseOption.h \
    ../Common/Qt/Options/SwitchDate/SwitchDateBaseWidget.h \
    ../Common/Qt/Options/TimeExpression/TimeExpressionBaseOption.h \
    ../Common/Qt/Options/TimeExpression/TimeExpressionBaseWidget.h \
    ../Common/Qt/QtJsonTools.h \
    ../Common/NintendoSwitch/NintendoSwitch_ControllerDefs.h \
    Source/CommonFramework/AudioPipeline/AudioConstants.h \
    Source/CommonFramework/AudioPipeline/AudioDisplayWidget.h \
    Source/CommonFramework/AudioPipeline/AudioFeed.h \
    Source/CommonFramework/AudioPipeline/AudioFileLoader.h \
    Source/CommonFramework/AudioPipeline/AudioFormatUtils.h \
    Source/CommonFramework/AudioPipeline/AudioIODevice.h \
    Source/CommonFramework/AudioPipeline/AudioInfo.h \
    Source/CommonFramework/AudioPipeline/AudioNormalization.h \
    Source/CommonFramework/AudioPipeline/AudioSelector.h \
    Source/CommonFramework/AudioPipeline/AudioSelectorWidget.h \
    Source/CommonFramework/AudioPipeline/AudioTemplate.h \
    Source/CommonFramework/AudioPipeline/AudioThreadController.h \
    Source/CommonFramework/AudioPipeline/AudioWorker.h \
    Source/CommonFramework/AudioPipeline/FFTWorker.h \
    Source/CommonFramework/AudioPipeline/TimeSampleBuffer.h \
    Source/CommonFramework/AudioPipeline/TimeSampleBufferReader.h \
    Source/CommonFramework/AudioPipeline/TimeSampleWriter.h \
    Source/CommonFramework/AudioPipeline/WavFile.h \
    Source/CommonFramework/ControllerDevices/SerialSelector.h \
    Source/CommonFramework/ControllerDevices/SerialSelectorWidget.h \
    Source/CommonFramework/CrashDump.h \
    Source/CommonFramework/Environment/Environment.h \
    Source/CommonFramework/Environment/HardwareValidation.h \
    Source/CommonFramework/GlobalSettingsPanel.h \
    Source/CommonFramework/Globals.h \
    Source/CommonFramework/ImageMatch/CroppedImageDictionaryMatcher.h \
    Source/CommonFramework/ImageMatch/ExactImageDictionaryMatcher.h \
    Source/CommonFramework/ImageMatch/ExactImageMatcher.h \
    Source/CommonFramework/ImageMatch/FilterToAlpha.h \
    Source/CommonFramework/ImageMatch/ImageCropper.h \
    Source/CommonFramework/ImageMatch/ImageDiff.h \
    Source/CommonFramework/ImageMatch/ImageMatchOption.h \
    Source/CommonFramework/ImageMatch/ImageMatchResult.h \
    Source/CommonFramework/ImageMatch/ScaleBrightness.h \
    Source/CommonFramework/ImageMatch/SilhouetteDictionaryMatcher.h \
    Source/CommonFramework/ImageMatch/SubObjectTemplateMatcher.h \
    Source/CommonFramework/ImageMatch/WaterfillTemplateMatcher.h \
    Source/CommonFramework/ImageTools/BinaryImage_FilterRgb32.h \
    Source/CommonFramework/ImageTools/ColorClustering.h \
    Source/CommonFramework/ImageTools/DistanceToLine.h \
    Source/CommonFramework/ImageTools/FloatPixel.h \
    Source/CommonFramework/ImageTools/ImageBoxes.h \
    Source/CommonFramework/ImageTools/ImageFilter.h \
    Source/CommonFramework/ImageTools/ImageStats.h \
    Source/CommonFramework/ImageTools/SolidColorTest.h \
    Source/CommonFramework/ImageTypes/BinaryImage.h \
    Source/CommonFramework/ImageTypes/ImageReference.h \
    Source/CommonFramework/Inference/AnomalyDetector.h \
    Source/CommonFramework/Inference/AudioPerSpectrumDetectorBase.h \
    Source/CommonFramework/Inference/AudioTemplateCache.h \
    Source/CommonFramework/Inference/BlackBorderDetector.h \
    Source/CommonFramework/Inference/BlackScreenDetector.h \
    Source/CommonFramework/Inference/DetectionDebouncer.h \
    Source/CommonFramework/Inference/FrozenImageDetector.h \
    Source/CommonFramework/Inference/ImageMatchDetector.h \
    Source/CommonFramework/Inference/ImageTools.h \
    Source/CommonFramework/Inference/InferenceThrottler.h \
    Source/CommonFramework/Inference/SpectrogramMatcher.h \
    Source/CommonFramework/Inference/StatAccumulator.h \
    Source/CommonFramework/Inference/TimeWindowStatTracker.h \
    Source/CommonFramework/Inference/VisualDetector.h \
    Source/CommonFramework/InferenceInfra/AudioInferenceCallback.h \
    Source/CommonFramework/InferenceInfra/AudioInferencePivot.h \
    Source/CommonFramework/InferenceInfra/InferenceCallback.h \
    Source/CommonFramework/InferenceInfra/InferenceRoutines.h \
    Source/CommonFramework/InferenceInfra/InferenceSession.h \
    Source/CommonFramework/InferenceInfra/VisualInferenceCallback.h \
    Source/CommonFramework/InferenceInfra/VisualInferencePivot.h \
    Source/CommonFramework/Language.h \
    Source/CommonFramework/Logging/FileWindowLogger.h \
    Source/CommonFramework/Logging/LoggerQt.h \
    Source/CommonFramework/Logging/OutputRedirector.h \
    Source/CommonFramework/Logging/QueuedLogger.h \
    Source/CommonFramework/Notifications/EventNotificationOption.h \
    Source/CommonFramework/Notifications/EventNotificationsTable.h \
    Source/CommonFramework/Notifications/MessageAttachment.h \
    Source/CommonFramework/Notifications/ProgramInfo.h \
    Source/CommonFramework/Notifications/ProgramNotifications.h \
    Source/CommonFramework/Notifications/SenderNotificationTable.h \
    Source/CommonFramework/OCR/OCR_DictionaryMatcher.h \
    Source/CommonFramework/OCR/OCR_DictionaryOCR.h \
    Source/CommonFramework/OCR/OCR_Filtering.h \
    Source/CommonFramework/OCR/OCR_LanguageOptionOCR.h \
    Source/CommonFramework/OCR/OCR_LargeDictionaryMatcher.h \
    Source/CommonFramework/OCR/OCR_NumberReader.h \
    Source/CommonFramework/OCR/OCR_RawOCR.h \
    Source/CommonFramework/OCR/OCR_Routines.h \
    Source/CommonFramework/OCR/OCR_SmallDictionaryMatcher.h \
    Source/CommonFramework/OCR/OCR_StringMatchResult.h \
    Source/CommonFramework/OCR/OCR_StringNormalization.h \
    Source/CommonFramework/OCR/OCR_TextMatcher.h \
    Source/CommonFramework/OCR/OCR_TrainingTools.h \
    Source/CommonFramework/OCR/TesseractPA.h \
    Source/CommonFramework/Options/BatchOption/BatchOption.h \
    Source/CommonFramework/Options/BatchOption/BatchWidget.h \
    Source/CommonFramework/Options/BatchOption/GroupOption.h \
    Source/CommonFramework/Options/BatchOption/GroupWidget.h \
    Source/CommonFramework/Options/BooleanCheckBoxOption.h \
    Source/CommonFramework/Options/ConfigOption.h \
    Source/CommonFramework/Options/EditableTableOption.h \
    Source/CommonFramework/Options/EnumDropdownOption.h \
    Source/CommonFramework/Options/EnumDropdownWidget.h \
    Source/CommonFramework/Options/Environment/ProcessPriorityOption.h \
    Source/CommonFramework/Options/Environment/ProcessorLevelOption.h \
    Source/CommonFramework/Options/FixedCodeOption.h \
    Source/CommonFramework/Options/FloatingPointOption.h \
    Source/CommonFramework/Options/HiddenTextEditOption.h \
    Source/CommonFramework/Options/RandomCodeOption.h \
    Source/CommonFramework/Options/ScreenshotFormatOption.h \
    Source/CommonFramework/Options/SimpleIntegerOption.h \
    Source/CommonFramework/Options/StaticTextOption.h \
    Source/CommonFramework/Options/StringOption.h \
    Source/CommonFramework/Options/StringSelectOption.h \
    Source/CommonFramework/Options/TextEditOption.h \
    Source/CommonFramework/Panels/Panel.h \
    Source/CommonFramework/Panels/PanelList.h \
    Source/CommonFramework/Panels/PanelWidget.h \
    Source/CommonFramework/Panels/RunnableComputerProgram.h \
    Source/CommonFramework/Panels/RunnableComputerProgramWidget.h \
    Source/CommonFramework/Panels/RunnablePanel.h \
    Source/CommonFramework/Panels/RunnablePanelWidget.h \
    Source/CommonFramework/Panels/SettingsPanel.h \
    Source/CommonFramework/Panels/SettingsPanelWidget.h \
    Source/CommonFramework/PersistentSettings.h \
    Source/CommonFramework/Tools/BlackBorderCheck.h \
    Source/CommonFramework/Tools/ConsoleHandle.h \
    Source/CommonFramework/Tools/ErrorDumper.h \
    Source/CommonFramework/Tools/InterruptableCommands.h \
    Source/CommonFramework/Tools/MultiConsoleErrors.h \
    Source/CommonFramework/Tools/ProgramEnvironment.h \
    Source/CommonFramework/Tools/StatsDatabase.h \
    Source/CommonFramework/Tools/StatsTracking.h \
    Source/CommonFramework/Tools/SuperControlSession.h \
    Source/CommonFramework/Tools/BotBaseHandle.h \
    Source/CommonFramework/VideoPipeline/CameraImplementations.h \
    Source/CommonFramework/VideoPipeline/CameraInfo.h \
    Source/CommonFramework/VideoPipeline/CameraSelector.h \
    Source/CommonFramework/VideoPipeline/CameraSelectorWidget.h \
    Source/CommonFramework/VideoPipeline/CameraWidgetQt5.h \
    Source/CommonFramework/VideoPipeline/CameraWidgetQt5v2.h \
    Source/CommonFramework/VideoPipeline/CameraWidgetQt6.h \
    Source/CommonFramework/VideoPipeline/VideoDisplayWidget.h \
    Source/CommonFramework/VideoPipeline/VideoFeed.h \
    Source/CommonFramework/VideoPipeline/VideoOverlay.h \
    Source/CommonFramework/VideoPipeline/VideoOverlayWidget.h \
    Source/CommonFramework/VideoPipeline/VideoToolsQt5.h \
    Source/CommonFramework/VideoPipeline/VideoWidget.h \
    Source/CommonFramework/Windows/ButtonDiagram.h \
    Source/CommonFramework/Windows/DpiScaler.h \
    Source/CommonFramework/Windows/MainWindow.h \
    Source/Integrations/DiscordIntegrationSettings.h \
    Source/Integrations/DiscordIntegrationTable.h \
    Source/Integrations/DiscordSettingsOption.h \
    Source/Integrations/DiscordWebhook.h \
    Source/Integrations/DiscordWebhookSettings.h \
    Source/Integrations/IntegrationsAPI.h \
    Source/Integrations/ProgramTracker.h \
    Source/Integrations/SleepyDiscordRunner.h \
    Source/Kernels/AbsFFT/Kernels_AbsFFT.h \
    Source/Kernels/AbsFFT/Kernels_AbsFFT_Arch.h \
    Source/Kernels/AbsFFT/Kernels_AbsFFT_Arch_Default.h \
    Source/Kernels/AbsFFT/Kernels_AbsFFT_Arch_x86_AVX2.h \
    Source/Kernels/AbsFFT/Kernels_AbsFFT_Arch_x86_SSE41.h \
    Source/Kernels/AbsFFT/Kernels_AbsFFT_BaseTransform_x86_AVX2.h \
    Source/Kernels/AbsFFT/Kernels_AbsFFT_BaseTransform_x86_SSE41.h \
    Source/Kernels/AbsFFT/Kernels_AbsFFT_BitReverse.h \
    Source/Kernels/AbsFFT/Kernels_AbsFFT_Butterflies.h \
    Source/Kernels/AbsFFT/Kernels_AbsFFT_ComplexScalar.h \
    Source/Kernels/AbsFFT/Kernels_AbsFFT_ComplexToAbs.h \
    Source/Kernels/AbsFFT/Kernels_AbsFFT_ComplexVector.h \
    Source/Kernels/AbsFFT/Kernels_AbsFFT_FullTransform.h \
    Source/Kernels/AbsFFT/Kernels_AbsFFT_FullTransform.tpp \
    Source/Kernels/AbsFFT/Kernels_AbsFFT_Reductions.h \
    Source/Kernels/AbsFFT/Kernels_AbsFFT_TwiddleTable.h \
    Source/Kernels/AbsFFT/Kernels_AbsFFT_TwiddleTable.tpp \
    Source/Kernels/BinaryImageFilters/Kernels_BinaryImage_BasicFilters.h \
    Source/Kernels/BinaryImageFilters/Kernels_BinaryImage_BasicFilters_Default.h \
    Source/Kernels/BinaryImageFilters/Kernels_BinaryImage_BasicFilters_Routines.h \
    Source/Kernels/BinaryImageFilters/Kernels_BinaryImage_BasicFilters_x64_AVX2.h \
    Source/Kernels/BinaryImageFilters/Kernels_BinaryImage_BasicFilters_x64_AVX512.h \
    Source/Kernels/BinaryImageFilters/Kernels_BinaryImage_BasicFilters_x64_SSE42.h \
    Source/Kernels/BinaryMatrix/Kernels_BinaryMatrix.h \
    Source/Kernels/BinaryMatrix/Kernels_BinaryMatrixTile_64x16_x64_AVX2.h \
    Source/Kernels/BinaryMatrix/Kernels_BinaryMatrixTile_64x32_x64_AVX512.h \
    Source/Kernels/BinaryMatrix/Kernels_BinaryMatrixTile_64x4_Default.h \
    Source/Kernels/BinaryMatrix/Kernels_BinaryMatrixTile_64x64_x64_AVX512.h \
    Source/Kernels/BinaryMatrix/Kernels_BinaryMatrixTile_64x8_x64_SSE42.h \
    Source/Kernels/BinaryMatrix/Kernels_BinaryMatrixTile_Debugging.h \
    Source/Kernels/BinaryMatrix/Kernels_BinaryMatrix_Arch_64x16_x64_AVX2.h \
    Source/Kernels/BinaryMatrix/Kernels_BinaryMatrix_Arch_64x32_x64_AVX512.h \
    Source/Kernels/BinaryMatrix/Kernels_BinaryMatrix_Arch_64x4_Default.h \
    Source/Kernels/BinaryMatrix/Kernels_BinaryMatrix_Arch_64x64_x64_AVX512.h \
    Source/Kernels/BinaryMatrix/Kernels_BinaryMatrix_Arch_64x8_x64_SSE42.h \
    Source/Kernels/BinaryMatrix/Kernels_BinaryMatrix_t.h \
    Source/Kernels/BinaryMatrix/Kernels_PackedBinaryMatrixCore.h \
    Source/Kernels/BinaryMatrix/Kernels_PackedBinaryMatrixCore.tpp \
    Source/Kernels/BinaryMatrix/Kernels_SparseBinaryMatrixCore.h \
    Source/Kernels/BinaryMatrix/Kernels_SparseBinaryMatrixCore.tpp \
    Source/Kernels/ImageFilters/Kernels_ImageFilter_Basic.h \
    Source/Kernels/ImageScaleBrightness/Kernels_ImageScaleBrightness.h \
    Source/Kernels/ImageStats/Kernels_ImagePixelSumSqr.h \
    Source/Kernels/ImageStats/Kernels_ImagePixelSumSqrDev.h \
    Source/Kernels/Kernels_Alignment.h \
    Source/Kernels/Kernels_Arch.h \
    Source/Kernels/Kernels_BitScan.h \
    Source/Kernels/Kernels_BitSet.h \
    Source/Kernels/Kernels_x64_AVX2.h \
    Source/Kernels/Kernels_x64_AVX512.h \
    Source/Kernels/Kernels_x64_SSE41.h \
    Source/Kernels/PartialWordAccess/Kernels_PartialWordAccess_x64_AVX2.h \
    Source/Kernels/PartialWordAccess/Kernels_PartialWordAccess_x64_SSE41.h \
    Source/Kernels/Waterfill/Kernels_Waterfill.h \
    Source/Kernels/Waterfill/Kernels_Waterfill_Core_64x16_x64_AVX2.h \
    Source/Kernels/Waterfill/Kernels_Waterfill_Core_64x32_x64_AVX512-GF.h \
    Source/Kernels/Waterfill/Kernels_Waterfill_Core_64x32_x64_AVX512.h \
    Source/Kernels/Waterfill/Kernels_Waterfill_Core_64x4_Default.h \
    Source/Kernels/Waterfill/Kernels_Waterfill_Core_64x64_x64_AVX512-GF.h \
    Source/Kernels/Waterfill/Kernels_Waterfill_Core_64x64_x64_AVX512.h \
    Source/Kernels/Waterfill/Kernels_Waterfill_Core_64x8_x64_SSE42.h \
    Source/Kernels/Waterfill/Kernels_Waterfill_Intrinsics_x64_AVX512.h \
    Source/Kernels/Waterfill/Kernels_Waterfill_Routines.h \
    Source/Kernels/Waterfill/Kernels_Waterfill_Session.h \
    Source/Kernels/Waterfill/Kernels_Waterfill_Session.tpp \
    Source/Kernels/Waterfill/Kernels_Waterfill_Types.h \
    Source/Kernels/Waterfill/Kernels_Waterfill_Intrinsics_x64_AVX512-GF.h \
    Source/NintendoSwitch/Commands/NintendoSwitch_Commands_Device.h \
    Source/NintendoSwitch/Commands/NintendoSwitch_Commands_DigitEntry.h \
    Source/NintendoSwitch/Commands/NintendoSwitch_Commands_PushButtons.h \
    Source/NintendoSwitch/Commands/NintendoSwitch_Commands_Routines.h \
    Source/NintendoSwitch/Commands/NintendoSwitch_Messages_Device.h \
    Source/NintendoSwitch/Commands/NintendoSwitch_Messages_DigitEntry.h \
    Source/NintendoSwitch/Commands/NintendoSwitch_Messages_PushButtons.h \
    Source/NintendoSwitch/Commands/NintendoSwitch_Messages_Routines.h \
    Source/NintendoSwitch/FixedInterval.h \
    Source/NintendoSwitch/Framework/NintendoSwitch_CommandRow.h \
    Source/NintendoSwitch/Framework/NintendoSwitch_MultiSwitchProgram.h \
    Source/NintendoSwitch/Framework/NintendoSwitch_MultiSwitchProgramWidget.h \
    Source/NintendoSwitch/Framework/NintendoSwitch_MultiSwitchSystem.h \
    Source/NintendoSwitch/Framework/NintendoSwitch_MultiSwitchSystemWidget.h \
    Source/NintendoSwitch/Framework/NintendoSwitch_RunnableProgram.h \
    Source/NintendoSwitch/Framework/NintendoSwitch_RunnableProgramWidget.h \
    Source/NintendoSwitch/Framework/NintendoSwitch_SingleSwitchProgram.h \
    Source/NintendoSwitch/Framework/NintendoSwitch_SingleSwitchProgramWidget.h \
    Source/NintendoSwitch/Framework/NintendoSwitch_SwitchSetup.h \
    Source/NintendoSwitch/Framework/NintendoSwitch_SwitchSetupWidget.h \
    Source/NintendoSwitch/Framework/NintendoSwitch_SwitchSystem.h \
    Source/NintendoSwitch/Framework/NintendoSwitch_SwitchSystemWidget.h \
    Source/NintendoSwitch/Framework/NintendoSwitch_VirtualController.h \
    Source/NintendoSwitch/Framework/NintendoSwitch_VirtualControllerMapping.h \
    Source/NintendoSwitch/Framework/NintendoSwitch_VirtualControllerState.h \
    Source/NintendoSwitch/InferenceTraining/PokemonHome_GenerateNameOCR.h \
    Source/NintendoSwitch/NintendoSwitch_Panels.h \
    Source/NintendoSwitch/NintendoSwitch_Settings.h \
    Source/NintendoSwitch/Options/GoHomeWhenDoneOption.h \
    Source/NintendoSwitch/Options/NintendoSwitch_FriendCodeListOption.h \
    Source/NintendoSwitch/Options/StartInGripMenuOption.h \
    Source/NintendoSwitch/Options/SwitchDateOption.h \
    Source/NintendoSwitch/Options/TimeExpressionOption.h \
    Source/NintendoSwitch/Programs/NintendoSwitch_FriendCodeAdder.h \
    Source/NintendoSwitch/Programs/NintendoSwitch_FriendDelete.h \
    Source/NintendoSwitch/Programs/NintendoSwitch_GameEntry.h \
    Source/NintendoSwitch/Programs/NintendoSwitch_PreventSleep.h \
    Source/NintendoSwitch/Programs/NintendoSwitch_SwitchViewer.h \
    Source/NintendoSwitch/Programs/NintendoSwitch_TurboA.h \
    Source/NintendoSwitch/Programs/NintendoSwitch_TurboButton.h \
    Source/NintendoSwitch/Programs/NintendoSwitch_VirtualConsole.h \
    Source/NintendoSwitch/Programs/PokemonHome_PageSwap.h \
    Source/NintendoSwitch/TestProgramComputer.h \
    Source/NintendoSwitch/TestProgramSwitch.h \
    Source/PanelLists.h \
    Source/Pokemon/Inference/Pokemon_BerryNameReader.h \
    Source/Pokemon/Inference/Pokemon_IVCheckerReader.h \
    Source/Pokemon/Inference/Pokemon_NameReader.h \
    Source/Pokemon/Inference/Pokemon_PokeballNameReader.h \
    Source/Pokemon/Inference/Pokemon_TrainIVCheckerOCR.h \
    Source/Pokemon/Inference/Pokemon_TrainPokemonOCR.h \
    Source/Pokemon/Options/Pokemon_BallSelectOption.h \
    Source/Pokemon/Options/Pokemon_BallSelectWidget.h \
    Source/Pokemon/Options/Pokemon_BerrySelectWidget.h \
    Source/Pokemon/Options/Pokemon_EncounterBotOptions.h \
    Source/Pokemon/Options/Pokemon_IVCheckerOption.h \
    Source/Pokemon/Options/Pokemon_IVCheckerWidget.h \
    Source/Pokemon/Options/Pokemon_NameListOption.h \
    Source/Pokemon/Options/Pokemon_NameSelectOption.h \
    Source/Pokemon/Options/Pokemon_NameSelectWidget.h \
    Source/Pokemon/Pokemon_DataTypes.h \
    Source/Pokemon/Pokemon_EncounterStats.h \
    Source/Pokemon/Pokemon_IVChecker.h \
    Source/Pokemon/Pokemon_Notification.h \
    Source/Pokemon/Pokemon_ShinySparkleSet.h \
    Source/Pokemon/Pokemon_Types.h \
    Source/Pokemon/Resources/Pokemon_BerryNames.h \
    Source/Pokemon/Resources/Pokemon_BerrySprites.h \
    Source/Pokemon/Resources/Pokemon_PokeballNames.h \
    Source/Pokemon/Resources/Pokemon_PokemonNames.h \
    Source/Pokemon/Resources/Pokemon_PokemonSlugs.h \
    Source/PokemonBDSP/Inference/Battles/PokemonBDSP_BattleBallReader.h \
    Source/PokemonBDSP/Inference/Battles/PokemonBDSP_BattleMenuDetector.h \
    Source/PokemonBDSP/Inference/Battles/PokemonBDSP_EndBattleDetector.h \
    Source/PokemonBDSP/Inference/Battles/PokemonBDSP_ExperienceGainDetector.h \
    Source/PokemonBDSP/Inference/Battles/PokemonBDSP_StartBattleDetector.h \
    Source/PokemonBDSP/Inference/BoxSystem/PokemonBDSP_BoxDetector.h \
    Source/PokemonBDSP/Inference/BoxSystem/PokemonBDSP_BoxShinyDetector.h \
    Source/PokemonBDSP/Inference/BoxSystem/PokemonBDSP_IVCheckerReader.h \
    Source/PokemonBDSP/Inference/PokemonBDSP_DialogDetector.h \
    Source/PokemonBDSP/Inference/PokemonBDSP_MapDetector.h \
    Source/PokemonBDSP/Inference/PokemonBDSP_MarkFinder.h \
    Source/PokemonBDSP/Inference/PokemonBDSP_MenuDetector.h \
    Source/PokemonBDSP/Inference/PokemonBDSP_PokeballSpriteMatcher.h \
    Source/PokemonBDSP/Inference/PokemonBDSP_ReceivePokemonDetector.h \
    Source/PokemonBDSP/Inference/PokemonBDSP_SelectionArrow.h \
    Source/PokemonBDSP/Inference/PokemonBDSP_VSSeekerReaction.h \
    Source/PokemonBDSP/Inference/ShinyDetection/PokemonBDSP_ShinyEncounterDetector.h \
    Source/PokemonBDSP/Inference/ShinyDetection/PokemonBDSP_ShinySparkleSet.h \
    Source/PokemonBDSP/Options/EncounterFilter/PokemonBDSP_EncounterFilterEnums.h \
    Source/PokemonBDSP/Options/EncounterFilter/PokemonBDSP_EncounterFilterOption.h \
    Source/PokemonBDSP/Options/EncounterFilter/PokemonBDSP_EncounterFilterOverride.h \
    Source/PokemonBDSP/Options/EncounterFilter/PokemonBDSP_EncounterFilterWidget.h \
    Source/PokemonBDSP/Options/PokemonBDSP_BerrySelector.h \
    Source/PokemonBDSP/Options/PokemonBDSP_EggHatchFilter.h \
    Source/PokemonBDSP/Options/PokemonBDSP_EncounterBotCommon.h \
    Source/PokemonBDSP/Options/PokemonBDSP_ShortcutDirection.h \
    Source/PokemonBDSP/Panels_PokemonBDSP.h \
    Source/PokemonBDSP/PokemonBDSP_Settings.h \
    Source/PokemonBDSP/Programs/Eggs/PokemonBDSP_EggAutonomous.h \
    Source/PokemonBDSP/Programs/Eggs/PokemonBDSP_EggAutonomousState.h \
    Source/PokemonBDSP/Programs/Eggs/PokemonBDSP_EggFeedback.h \
    Source/PokemonBDSP/Programs/Eggs/PokemonBDSP_EggFetcher.h \
    Source/PokemonBDSP/Programs/Eggs/PokemonBDSP_EggHatcher.h \
    Source/PokemonBDSP/Programs/Eggs/PokemonBDSP_EggRoutines.h \
    Source/PokemonBDSP/Programs/Farming/PokemonBDSP_AmitySquarePickUpFarmer.h \
    Source/PokemonBDSP/Programs/Farming/PokemonBDSP_DoublesLeveling.h \
    Source/PokemonBDSP/Programs/Farming/PokemonBDSP_GiftBerryReset.h \
    Source/PokemonBDSP/Programs/Farming/PokemonBDSP_MoneyFarmerRoute210.h \
    Source/PokemonBDSP/Programs/Farming/PokemonBDSP_MoneyFarmerRoute212.h \
    Source/PokemonBDSP/Programs/General/PokemonBDSP_AutonomousBallThrower.h \
    Source/PokemonBDSP/Programs/General/PokemonBDSP_MassRelease.h \
    Source/PokemonBDSP/Programs/Glitches/PokemonBDSP_ActivateMenuGlitch-1.1.3.h \
    Source/PokemonBDSP/Programs/Glitches/PokemonBDSP_ActivateMenuGlitch-1.1.2.h \
    Source/PokemonBDSP/Programs/Glitches/PokemonBDSP_CloneItemsBoxCopy.h \
    Source/PokemonBDSP/Programs/Glitches/PokemonBDSP_CloneItemsBoxCopy2.h \
    Source/PokemonBDSP/Programs/Glitches/PokemonBDSP_CloneItemsMenuOverlap.h \
    Source/PokemonBDSP/Programs/Glitches/PokemonBDSP_MenuOverlap.h \
    Source/PokemonBDSP/Programs/PokemonBDSP_BasicCatcher.h \
    Source/PokemonBDSP/Programs/PokemonBDSP_BoxRelease.h \
    Source/PokemonBDSP/Programs/PokemonBDSP_EncounterDetection.h \
    Source/PokemonBDSP/Programs/PokemonBDSP_EncounterHandler.h \
    Source/PokemonBDSP/Programs/PokemonBDSP_GameEntry.h \
    Source/PokemonBDSP/Programs/PokemonBDSP_GameNavigation.h \
    Source/PokemonBDSP/Programs/PokemonBDSP_GlobalRoomHeal.h \
    Source/PokemonBDSP/Programs/PokemonBDSP_OverworldTrigger.h \
    Source/PokemonBDSP/Programs/PokemonBDSP_RunFromBattle.h \
    Source/PokemonBDSP/Programs/ShinyHunting/PokemonBDSP_LegendaryReset.h \
    Source/PokemonBDSP/Programs/ShinyHunting/PokemonBDSP_ShinyHunt-Fishing.h \
    Source/PokemonBDSP/Programs/ShinyHunting/PokemonBDSP_ShinyHunt-Overworld.h \
    Source/PokemonBDSP/Programs/ShinyHunting/PokemonBDSP_ShinyHunt-Shaymin.h \
    Source/PokemonBDSP/Programs/ShinyHunting/PokemonBDSP_StarterReset.h \
    Source/PokemonBDSP/Programs/Trading/PokemonBDSP_SelfBoxTrade.h \
    Source/PokemonBDSP/Programs/Trading/PokemonBDSP_SelfTouchTrade.h \
    Source/PokemonBDSP/Programs/Trading/PokemonBDSP_TradeRoutines.h \
    Source/PokemonLA/Inference/Battles/PokemonLA_BattleMenuDetector.h \
    Source/PokemonLA/Inference/Battles/PokemonLA_BattleMoveSelectionDetector.h \
    Source/PokemonLA/Inference/Battles/PokemonLA_BattlePokemonSwitchDetector.h \
    Source/PokemonLA/Inference/Objects/PokemonLA_ArcDetector.h \
    Source/PokemonLA/Inference/Objects/PokemonLA_ArcPhoneDetector.h \
    Source/PokemonLA/Inference/Objects/PokemonLA_BubbleDetector.h \
    Source/PokemonLA/Inference/Objects/PokemonLA_ButtonDetector.h \
    Source/PokemonLA/Inference/Objects/PokemonLA_DialogueEllipseDetector.h \
    Source/PokemonLA/Inference/Objects/PokemonLA_FlagDetector.h \
    Source/PokemonLA/Inference/Objects/PokemonLA_FlagTracker.h \
    Source/PokemonLA/Inference/Objects/PokemonLA_QuestMarkDetector.h \
    Source/PokemonLA/Inference/Objects/PokemonLA_ShinySymbolDetector.h \
    Source/PokemonLA/Inference/Objects/PokemonLA_WhiteObjectDetector.h \
    Source/PokemonLA/Inference/PokemonLA_CommonColorCheck.h \
    Source/PokemonLA/Inference/PokemonLA_DialogDetector.h \
    Source/PokemonLA/Inference/PokemonLA_ItemCompatibilityDetector.h \
    Source/PokemonLA/Inference/PokemonLA_MapDetector.h \
    Source/PokemonLA/Inference/PokemonLA_MountDetector.h \
    Source/PokemonLA/Inference/PokemonLA_NotificationReader.h \
    Source/PokemonLA/Inference/PokemonLA_OutbreakReader.h \
    Source/PokemonLA/Inference/PokemonLA_OverworldDetector.h \
    Source/PokemonLA/Inference/PokemonLA_SelectedRegionDetector.h \
    Source/PokemonLA/Inference/PokemonLA_StatusInfoScreenDetector.h \
    Source/PokemonLA/Inference/PokemonLA_UnderAttackDetector.h \
    Source/PokemonLA/Inference/Sounds/PokemonLA_AlphaMusicDetector.h \
    Source/PokemonLA/Inference/Sounds/PokemonLA_AlphaRoarDetector.h \
    Source/PokemonLA/Inference/Sounds/PokemonLA_ShinySoundDetector.h \
    Source/PokemonLA/Options/PokemonLA_BattlePokemonActionTable.h \
    Source/PokemonLA/Options/PokemonLA_CustomPathTable.h \
    Source/PokemonLA/Options/PokemonLA_ShinyDetectedAction.h \
    Source/PokemonLA/Options/PokemonLA_TradeCountTable.h \
    Source/PokemonLA/Options/PokemonLA_TravelLocation.h \
    Source/PokemonLA/Panels_PokemonLA.h \
    Source/PokemonLA/PokemonLA_Locations.h \
    Source/PokemonLA/PokemonLA_Settings.h \
    Source/PokemonLA/PokemonLA_TravelLocations.h \
    Source/PokemonLA/Programs/Farming/PokemonLA_MagikarpMoveGrinder.h \
    Source/PokemonLA/Programs/Farming/PokemonLA_TenacityCandyFarmer.h \
    Source/PokemonLA/Programs/General/PokemonLA_ClothingBuyer.h \
    Source/PokemonLA/Programs/General/PokemonLA_SkipToFullMoon.h \
    Source/PokemonLA/Programs/PokemonLA_BattleRoutines.h \
    Source/PokemonLA/Programs/PokemonLA_BraviaryHeightGlitch.h \
    Source/PokemonLA/Programs/PokemonLA_DistortionWaiter.h \
    Source/PokemonLA/Programs/PokemonLA_EscapeFromAttack.h \
    Source/PokemonLA/Programs/PokemonLA_FlagNavigationAir.h \
    Source/PokemonLA/Programs/PokemonLA_GameEntry.h \
    Source/PokemonLA/Programs/PokemonLA_MountChange.h \
    Source/PokemonLA/Programs/PokemonLA_OutbreakFinder.h \
    Source/PokemonLA/Programs/PokemonLA_RegionNavigation.h \
    Source/PokemonLA/Programs/ShinyHunting/PokemonLA_PostMMOSpawnReset.h \
    Source/PokemonLA/Programs/ShinyHunting/PokemonLA_ShinyHunt-CustomPath.h \
    Source/PokemonLA/Programs/TestPrograms/PokemonLA_AlphaMusicListener.h \
    Source/PokemonLA/Programs/TestPrograms/PokemonLA_AlphaRoarListener.h \
    Source/PokemonLA/Programs/TestPrograms/PokemonLA_MountDetectionTest.h \
    Source/PokemonLA/Programs/Trading/PokemonLA_SelfBoxTrade.h \
    Source/PokemonLA/Programs/Trading/PokemonLA_SelfTouchTrade.h \
    Source/PokemonLA/Programs/Trading/PokemonLA_TradeRoutines.h \
    Source/PokemonLA/Programs/Farming/PokemonLA_NuggetFarmerHighlands.h \
    Source/PokemonLA/Programs/Farming/PokemonLA_IngoBattleGrinder.h \
    Source/PokemonLA/Programs/ShinyHunting/PokemonLA_CrobatFinder.h \
    Source/PokemonLA/Programs/ShinyHunting/PokemonLA_GalladeFinder.h \
    Source/PokemonLA/Programs/ShinyHunting/PokemonLA_FroslassFinder.h \
    Source/PokemonLA/Programs/ShinyHunting/PokemonLA_TreeShinyHunting.h \
    Source/PokemonLA/Programs/ShinyHunting/PokemonLA_UnownFinder.h \
    Source/PokemonLA/Programs/ShinyHunting/PokemonLA_ShinyHunt-FlagPin.h \
    Source/PokemonLA/Programs/ShinyHunting/PokemonLA_ShinyHunt-LakeTrio.h \
    Source/PokemonLA/Programs/TestPrograms/PokemonLA_FlagNavigationTest.h \
    Source/PokemonLA/Programs/TestPrograms/PokemonLA_OverworldWatcher.h \
    Source/PokemonLA/Programs/TestPrograms/PokemonLA_ShinySoundListener.h \
    Source/PokemonLA/Resources/PokemonLA_AvailablePokemon.h \
    Source/PokemonLA/Resources/PokemonLA_PokemonIcons.h \
    Source/PokemonSwSh/Commands/PokemonSwSh_Commands_AutoHosts.h \
    Source/PokemonSwSh/Commands/PokemonSwSh_Commands_DateSpam.h \
    Source/PokemonSwSh/Commands/PokemonSwSh_Commands_DaySkippers.h \
    Source/PokemonSwSh/Commands/PokemonSwSh_Commands_EggRoutines.h \
    Source/PokemonSwSh/Commands/PokemonSwSh_Commands_GameEntry.h \
    Source/PokemonSwSh/Commands/PokemonSwSh_Commands_Misc.h \
    Source/PokemonSwSh/Commands/PokemonSwSh_Messages_AutoHosts.h \
    Source/PokemonSwSh/Commands/PokemonSwSh_Messages_DateSpam.h \
    Source/PokemonSwSh/Commands/PokemonSwSh_Messages_DaySkippers.h \
    Source/PokemonSwSh/Commands/PokemonSwSh_Messages_EggRoutines.h \
    Source/PokemonSwSh/Commands/PokemonSwSh_Messages_GameEntry.h \
    Source/PokemonSwSh/Commands/PokemonSwSh_Messages_Misc.h \
    Source/PokemonSwSh/Inference/Battles/PokemonSwSh_BattleBallReader.h \
    Source/PokemonSwSh/Inference/Battles/PokemonSwSh_BattleDialogDetector.h \
    Source/PokemonSwSh/Inference/Battles/PokemonSwSh_BattleDialogTracker.h \
    Source/PokemonSwSh/Inference/Battles/PokemonSwSh_BattleMenuDetector.h \
    Source/PokemonSwSh/Inference/Battles/PokemonSwSh_ExperienceGainDetector.h \
    Source/PokemonSwSh/Inference/Battles/PokemonSwSh_StartBattleDetector.h \
    Source/PokemonSwSh/Inference/Dens/PokemonSwSh_BeamSetter.h \
    Source/PokemonSwSh/Inference/Dens/PokemonSwSh_DenMonReader.h \
    Source/PokemonSwSh/Inference/Dens/PokemonSwSh_RaidCatchDetector.h \
    Source/PokemonSwSh/Inference/Dens/PokemonSwSh_RaidLobbyReader.h \
    Source/PokemonSwSh/Inference/PokemonSwSh_FishingDetector.h \
    Source/PokemonSwSh/Inference/PokemonSwSh_IVCheckerReader.h \
    Source/PokemonSwSh/Inference/PokemonSwSh_MarkFinder.h \
    Source/PokemonSwSh/Inference/PokemonSwSh_PokemonSpriteReader.h \
    Source/PokemonSwSh/Inference/PokemonSwSh_PromptDetector.h \
    Source/PokemonSwSh/Inference/PokemonSwSh_QuantityReader.h \
    Source/PokemonSwSh/Inference/PokemonSwSh_ReceivePokemonDetector.h \
    Source/PokemonSwSh/Inference/PokemonSwSh_SelectionArrowFinder.h \
    Source/PokemonSwSh/Inference/PokemonSwSh_SummaryShinySymbolDetector.h \
    Source/PokemonSwSh/Inference/PokemonSwSh_TypeSymbolFinder.h \
    Source/PokemonSwSh/Inference/PokemonSwSh_YCommDetector.h \
    Source/PokemonSwSh/Inference/ShinyDetection/PokemonSwSh_ShinyEncounterDetector.h \
    Source/PokemonSwSh/Inference/ShinyDetection/PokemonSwSh_ShinySparkleSet.h \
    Source/PokemonSwSh/Inference/ShinyDetection/PokemonSwSh_SparkleDetectorRadial.h \
    Source/PokemonSwSh/Inference/ShinyDetection/PokemonSwSh_SparkleDetectorSquare.h \
    Source/PokemonSwSh/InferenceTraining/PokemonSwSh_GenerateIVCheckerOCR.h \
    Source/PokemonSwSh/InferenceTraining/PokemonSwSh_GenerateNameOCRPokedex.h \
    Source/PokemonSwSh/MaxLair/AI/PokemonSwSh_MaxLair_AI.h \
    Source/PokemonSwSh/MaxLair/AI/PokemonSwSh_MaxLair_AI_PathMatchup.h \
    Source/PokemonSwSh/MaxLair/AI/PokemonSwSh_MaxLair_AI_RentalBossMatchup.h \
    Source/PokemonSwSh/MaxLair/AI/PokemonSwSh_MaxLair_AI_Tools.h \
    Source/PokemonSwSh/MaxLair/Framework/PokemonSwSh_MaxLair_CatchScreenTracker.h \
    Source/PokemonSwSh/MaxLair/Inference/PokemonSwSh_MaxLair_Detect_PathMap.h \
    Source/PokemonSwSh/MaxLair/Inference/PokemonSwSh_MaxLair_Detect_PathSide.h \
    Source/PokemonSwSh/MaxLair/Inference/PokemonSwSh_MaxLair_Detect_ProfessorSwap.h \
    Source/PokemonSwSh/MaxLair/Options/PokemonSwSh_MaxLair_Options.h \
    Source/PokemonSwSh/MaxLair/Options/PokemonSwSh_MaxLair_Options_BossAction.h \
    Source/PokemonSwSh/MaxLair/Options/PokemonSwSh_MaxLair_Options_Consoles.h \
    Source/PokemonSwSh/MaxLair/Options/PokemonSwSh_MaxLair_Options_Hosting.h \
    Source/PokemonSwSh/MaxLair/PokemonSwSh_MaxLair_BossFinder.h \
    Source/PokemonSwSh/MaxLair/PokemonSwSh_MaxLair_StrongBoss.h \
    Source/PokemonSwSh/MaxLair/Program/PokemonSwSh_MaxLair_Run_Adventure.h \
    Source/PokemonSwSh/MaxLair/Program/PokemonSwSh_MaxLair_Run_EnterLobby.h \
    Source/PokemonSwSh/MaxLair/Program/PokemonSwSh_MaxLair_Run_ProfessorSwap.h \
    Source/PokemonSwSh/MaxLair/Program/PokemonSwSh_MaxLair_Run_StartSolo.h \
    Source/PokemonSwSh/Options/EncounterFilter/PokemonSwSh_EncounterFilterEnums.h \
    Source/PokemonSwSh/Options/EncounterFilter/PokemonSwSh_EncounterFilterOption.h \
    Source/PokemonSwSh/Options/EncounterFilter/PokemonSwSh_EncounterFilterOverride.h \
    Source/PokemonSwSh/Options/EncounterFilter/PokemonSwSh_EncounterFilterWidget.h \
    Source/PokemonSwSh/Options/PokemonSwSh_AutoHostNotification.h \
    Source/PokemonSwSh/Options/PokemonSwSh_Catchability.h \
    Source/PokemonSwSh/Options/PokemonSwSh_DateToucher.h \
    Source/PokemonSwSh/Options/PokemonSwSh_EggStepCount.h \
    Source/PokemonSwSh/Options/PokemonSwSh_EncounterBotCommon.h \
    Source/PokemonSwSh/Options/PokemonSwSh_FossilTable.h \
    Source/PokemonSwSh/Options/PokemonSwSh_MultiHostTable.h \
    Source/PokemonSwSh/Options/PokemonSwSh_RegiSelector.h \
    Source/PokemonSwSh/PkmnLib/PokemonSwSh_PkmnLib_Battle.h \
    Source/PokemonSwSh/PkmnLib/PokemonSwSh_PkmnLib_Field.h \
    Source/PokemonSwSh/PkmnLib/PokemonSwSh_PkmnLib_Matchup.h \
    Source/PokemonSwSh/PkmnLib/PokemonSwSh_PkmnLib_Moves.h \
    Source/PokemonSwSh/PkmnLib/PokemonSwSh_PkmnLib_Pokemon.h \
    Source/PokemonSwSh/PkmnLib/PokemonSwSh_PkmnLib_Stats.h \
    Source/PokemonSwSh/PkmnLib/PokemonSwSh_PkmnLib_Types.h \
    Source/PokemonSwSh/PokemonSwSh_Panels.h \
    Source/PokemonSwSh/PokemonSwSh_Settings.h \
    Source/PokemonSwSh/Programs/DateSpamFarmers/PokemonSwSh_DateSpam-PokeJobsFarmer.h \
    Source/PokemonSwSh/Programs/DenHunting/PokemonSwSh_DaySkipperStats.h \
    Source/PokemonSwSh/Programs/EggPrograms/PokemonSwSh_EggFetcherMultiple.h \
    Source/PokemonSwSh/Programs/General/PokemonSwSh_AutonomousBallThrower.h \
    Source/PokemonSwSh/Programs/General/PokemonSwSh_BallThrower.h \
    Source/PokemonSwSh/Programs/General/PokemonSwSh_BoxReorderNationalDex.h \
    Source/PokemonSwSh/Programs/General/PokemonSwSh_ClothingBuyer.h \
    Source/PokemonSwSh/Programs/General/PokemonSwSh_DexRecFinder.h \
    Source/PokemonSwSh/Programs/General/PokemonSwSh_MassRelease.h \
    Source/PokemonSwSh/Programs/General/PokemonSwSh_SurpriseTrade.h \
    Source/PokemonSwSh/Programs/General/PokemonSwSh_TradeBot.h \
    Source/PokemonSwSh/Programs/Hosting/PokemonSwSh_AutoHost.h \
    Source/PokemonSwSh/Programs/Hosting/PokemonSwSh_AutoHostStats.h \
    Source/PokemonSwSh/MaxLair/Framework/PokemonSwSh_MaxLair_Notifications.h \
    Source/PokemonSwSh/MaxLair/Framework/PokemonSwSh_MaxLair_State.h \
    Source/PokemonSwSh/MaxLair/Framework/PokemonSwSh_MaxLair_StateMachine.h \
    Source/PokemonSwSh/MaxLair/Framework/PokemonSwSh_MaxLair_StateTracker.h \
    Source/PokemonSwSh/MaxLair/Framework/PokemonSwSh_MaxLair_Stats.h \
    Source/PokemonSwSh/MaxLair/Inference/PokemonSwSh_MaxLair_Detect_BattleMenu.h \
    Source/PokemonSwSh/MaxLair/Inference/PokemonSwSh_MaxLair_Detect_EndBattle.h \
    Source/PokemonSwSh/MaxLair/Inference/PokemonSwSh_MaxLair_Detect_Entrance.h \
    Source/PokemonSwSh/MaxLair/Inference/PokemonSwSh_MaxLair_Detect_HPPP.h \
    Source/PokemonSwSh/MaxLair/Inference/PokemonSwSh_MaxLair_Detect_ItemSelectMenu.h \
    Source/PokemonSwSh/MaxLair/Inference/PokemonSwSh_MaxLair_Detect_Lobby.h \
    Source/PokemonSwSh/MaxLair/Inference/PokemonSwSh_MaxLair_Detect_PathSelect.h \
    Source/PokemonSwSh/MaxLair/Inference/PokemonSwSh_MaxLair_Detect_PokemonReader.h \
    Source/PokemonSwSh/MaxLair/Inference/PokemonSwSh_MaxLair_Detect_PokemonSelectMenu.h \
    Source/PokemonSwSh/MaxLair/Inference/PokemonSwSh_MaxLair_Detect_PokemonSwapMenu.h \
    Source/PokemonSwSh/MaxLair/PokemonSwSh_MaxLair_Standard.h \
    Source/PokemonSwSh/MaxLair/Program/PokemonSwSh_MaxLair_Run_Battle.h \
    Source/PokemonSwSh/MaxLair/Program/PokemonSwSh_MaxLair_Run_CaughtScreen.h \
    Source/PokemonSwSh/MaxLair/Program/PokemonSwSh_MaxLair_Run_Entrance.h \
    Source/PokemonSwSh/MaxLair/Program/PokemonSwSh_MaxLair_Run_ItemSelect.h \
    Source/PokemonSwSh/MaxLair/Program/PokemonSwSh_MaxLair_Run_PathSelect.h \
    Source/PokemonSwSh/MaxLair/Program/PokemonSwSh_MaxLair_Run_PokemonSelect.h \
    Source/PokemonSwSh/MaxLair/Program/PokemonSwSh_MaxLair_Run_PokemonSwap.h \
    Source/PokemonSwSh/MaxLair/Program/PokemonSwSh_MaxLair_Run_Start.h \
    Source/PokemonSwSh/Programs/NonShinyHunting/PokemonSwSh_StatsReset-Calyrex.h \
    Source/PokemonSwSh/Programs/NonShinyHunting/PokemonSwSh_StatsReset-Moltres.h \
    Source/PokemonSwSh/Programs/NonShinyHunting/PokemonSwSh_StatsReset-Regi.h \
    Source/PokemonSwSh/Programs/NonShinyHunting/PokemonSwSh_StatsReset.h \
    Source/PokemonSwSh/Programs/OverworldBot/PokemonSwSh_OverworldMovement.h \
    Source/PokemonSwSh/Programs/OverworldBot/PokemonSwSh_OverworldTargetTracker.h \
    Source/PokemonSwSh/Programs/OverworldBot/PokemonSwSh_OverworldTrajectory.h \
    Source/PokemonSwSh/Programs/OverworldBot/PokemonSwSh_OverworldTrigger.h \
    Source/PokemonSwSh/Programs/OverworldBot/PokemonSwSh_ShinyHuntAutonomous-Overworld.h \
    Source/PokemonSwSh/Programs/PokemonSwSh_BasicCatcher.h \
    Source/PokemonSwSh/Programs/PokemonSwSh_EncounterDetection.h \
    Source/PokemonSwSh/Programs/PokemonSwSh_EncounterHandler.h \
    Source/PokemonSwSh/Programs/PokemonSwSh_Internet.h \
    Source/PokemonSwSh/Programs/PokemonSwSh_StartGame.h \
    Source/PokemonSwSh/Programs/ShinyHuntAutonomous/PokemonSwSh_ShinyHuntAutonomous-BerryTree.h \
    Source/PokemonSwSh/Programs/ShinyHuntAutonomous/PokemonSwSh_ShinyHuntAutonomous-Fishing.h \
    Source/PokemonSwSh/Programs/ShinyHuntAutonomous/PokemonSwSh_ShinyHuntAutonomous-IoATrade.h \
    Source/PokemonSwSh/Programs/ShinyHuntAutonomous/PokemonSwSh_ShinyHuntAutonomous-Regi.h \
    Source/PokemonSwSh/Programs/ShinyHuntAutonomous/PokemonSwSh_ShinyHuntAutonomous-Regigigas2.h \
    Source/PokemonSwSh/Programs/ShinyHuntAutonomous/PokemonSwSh_ShinyHuntAutonomous-StrongSpawn.h \
    Source/PokemonSwSh/Programs/ShinyHuntAutonomous/PokemonSwSh_ShinyHuntAutonomous-SwordsOfJustice.h \
    Source/PokemonSwSh/Programs/ShinyHuntAutonomous/PokemonSwSh_ShinyHuntAutonomous-Whistling.h \
    Source/PokemonSwSh/Programs/ShinyHuntUnattended/PokemonSwSh_CurryHunter.h \
    Source/PokemonSwSh/Programs/ShinyHuntUnattended/PokemonSwSh_MultiGameFossil.h \
    Source/PokemonSwSh/Programs/ShinyHuntUnattended/PokemonSwSh_ShinyHunt-Regi.h \
    Source/PokemonSwSh/Programs/ShinyHuntUnattended/PokemonSwSh_ShinyHuntTools.h \
    Source/PokemonSwSh/Programs/ShinyHuntUnattended/PokemonSwSh_ShinyHuntUnattended-IoATrade.h \
    Source/PokemonSwSh/Programs/ShinyHuntUnattended/PokemonSwSh_ShinyHuntUnattended-Regi.h \
    Source/PokemonSwSh/Programs/ShinyHuntUnattended/PokemonSwSh_ShinyHuntUnattended-Regigigas2.h \
    Source/PokemonSwSh/Programs/ShinyHuntUnattended/PokemonSwSh_ShinyHuntUnattended-StrongSpawn.h \
    Source/PokemonSwSh/Programs/ShinyHuntUnattended/PokemonSwSh_ShinyHuntUnattended-SwordsOfJustice.h \
    Source/PokemonSwSh/Programs/DateSpamFarmers/PokemonSwSh_DateSpam-BerryFarmer.h \
    Source/PokemonSwSh/Programs/DateSpamFarmers/PokemonSwSh_DateSpam-DailyHighlightFarmer.h \
    Source/PokemonSwSh/Programs/DateSpamFarmers/PokemonSwSh_DateSpam-LotoFarmer.h \
    Source/PokemonSwSh/Programs/DateSpamFarmers/PokemonSwSh_DateSpam-StowOnSideFarmer.h \
    Source/PokemonSwSh/Programs/DateSpamFarmers/PokemonSwSh_DateSpam-WattFarmer.h \
    Source/PokemonSwSh/Programs/DenHunting/PokemonSwSh_BeamReset.h \
    Source/PokemonSwSh/Programs/DenHunting/PokemonSwSh_DaySkipperEU.h \
    Source/PokemonSwSh/Programs/DenHunting/PokemonSwSh_DaySkipperJPN-7.8k.h \
    Source/PokemonSwSh/Programs/DenHunting/PokemonSwSh_DaySkipperJPN.h \
    Source/PokemonSwSh/Programs/DenHunting/PokemonSwSh_DaySkipperUS.h \
    Source/PokemonSwSh/Programs/DenHunting/PokemonSwSh_EventBeamFinder.h \
    Source/PokemonSwSh/Programs/DenHunting/PokemonSwSh_PurpleBeamFinder.h \
    Source/PokemonSwSh/Programs/EggPrograms/PokemonSwSh_EggCombined2.h \
    Source/PokemonSwSh/Programs/EggPrograms/PokemonSwSh_EggCombinedShared.h \
    Source/PokemonSwSh/Programs/EggPrograms/PokemonSwSh_EggFetcher2.h \
    Source/PokemonSwSh/Programs/EggPrograms/PokemonSwSh_EggHatcher.h \
    Source/PokemonSwSh/Programs/EggPrograms/PokemonSwSh_EggHelpers.h \
    Source/PokemonSwSh/Programs/EggPrograms/PokemonSwSh_EggSuperCombined2.h \
    Source/PokemonSwSh/Programs/EggPrograms/PokemonSwSh_GodEggDuplication.h \
    Source/PokemonSwSh/Programs/EggPrograms/PokemonSwSh_GodEggItemDupe.h \
    Source/PokemonSwSh/Programs/Hosting/PokemonSwSh_AutoHost-MultiGame.h \
    Source/PokemonSwSh/Programs/Hosting/PokemonSwSh_AutoHost-Rolling.h \
    Source/PokemonSwSh/Programs/Hosting/PokemonSwSh_DenRoller.h \
    Source/PokemonSwSh/Programs/Hosting/PokemonSwSh_DenTools.h \
    Source/PokemonSwSh/Programs/Hosting/PokemonSwSh_LobbyWait.h \
    Source/PokemonSwSh/Programs/PokemonSwSh_RaidItemFarmerOKHO.h \
    Source/PokemonSwSh/Programs/PokemonSwSh_SynchronizedSpinning.h \
    Source/PokemonSwSh/Programs/QoLMacros/PokemonSwSh_FastCodeEntry.h \
    Source/PokemonSwSh/Programs/QoLMacros/PokemonSwSh_FriendSearchDisconnect.h \
    Source/PokemonSwSh/Programs/ReleaseHelpers.h \
    Source/PokemonSwSh/Resources/PokemonSwSh_MaxLairDatabase.h \
    Source/PokemonSwSh/Resources/PokemonSwSh_PokeballSprites.h \
    Source/PokemonSwSh/Resources/PokemonSwSh_PokemonIcons.h \
    Source/PokemonSwSh/Resources/PokemonSwSh_PokemonSprites.h \
    Source/PokemonSwSh/Resources/PokemonSwSh_TypeMatchup.h \
    Source/PokemonSwSh/Resources/PokemonSwSh_TypeSprites.h \
    Source/PokemonSwSh/ShinyHuntTracker.h

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target
