/*  ML Object Annotation
 *
 *  From: https://github.com/PokemonAutomation/
 *
 *  Class to store the annotation manually done on an object in an image or video
 */

#ifndef PokemonAutomation_ML_ObjectAnnotation_H
#define PokemonAutomation_ML_ObjectAnnotation_H

#include <vector>
#include <string>
#include "Common/Cpp/Json/JsonValue.h"
#include "CommonFramework/ImageTools/ImageBoxes.h"


namespace PokemonAutomation{
namespace ML{


// Store annotation generated by user and ML model on one object
struct ObjectAnnotation{
    // user drawn loose bounding box
    ImagePixelBox user_box;
    // tight bounding box around a mask
    ImagePixelBox mask_box;
    // User added points to denote this point belongs to the object.
    // This is to help the automatic annotation model to compute the correct
    // per-pixel mask.
    std::vector<std::pair<size_t, size_t>> inclusion_points;
    // User added points to denote this point does not belong to the object.
    // This is to help the automatic annotation model to compute the correct
    // per-pixel mask.
    std::vector<std::pair<size_t, size_t>> exclusion_points;
    // per-pixel mask on whether this pixel belongs to the object
    // size() equals the total pixels in mask_box
    std::vector<bool> mask;
    // label of the object
    std::string label = "unknown";

    ObjectAnnotation();

    // if failed to pass, will throw JsonParseException
    static ObjectAnnotation from_json(const JsonValue& json);
    JsonValue to_json() const;
};


}
}
#endif